-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj_333_Zhou\hdlsrc\parallel_lht\Hough_Kernel_Symmetric.vhd
-- Created: 2020-02-27 22:35:22
-- 
-- Generated by MATLAB 9.7 and HDL Coder 3.15
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Hough_Kernel_Symmetric
-- Source Path: parallel_lht/Parallel LHT/Parallel LHT Kernel/Hough Kernel/Hough Kernel Symmetric Look Ahead/Hough 
-- Kernel Symmetri
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Parallel_LHT_pkg.ALL;

ENTITY Hough_Kernel_Symmetric IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        X                                 :   IN    std_logic_vector(8 DOWNTO 0);  -- sfix9
        ysin                              :   IN    vector_of_std_logic_vector9(0 TO 90);  -- sfix9 [91]
        Rho                               :   OUT   vector_of_std_logic_vector9(0 TO 179)  -- sfix9 [180]
        );
END Hough_Kernel_Symmetric;


ARCHITECTURE rtl OF Hough_Kernel_Symmetric IS

  -- Signals
  SIGNAL X_signed                         : signed(8 DOWNTO 0);  -- sfix9
  SIGNAL X_1                              : signed(8 DOWNTO 0);  -- sfix9
  SIGNAL Cosine_out1                      : vector_of_signed16(0 TO 89);  -- sfix16_En14 [90]
  SIGNAL Cosine_out1_1                    : vector_of_signed16(0 TO 89);  -- sfix16_En14 [90]
  SIGNAL xcos_out1                        : vector_of_signed25(0 TO 89);  -- sfix25_En14 [90]
  SIGNAL xcos_out1_1                      : vector_of_signed25(0 TO 89);  -- sfix25_En14 [90]
  SIGNAL xcos_out1_2                      : vector_of_signed9(0 TO 89);  -- sfix9 [90]
  SIGNAL Selector_out1                    : vector_of_signed9(0 TO 89);  -- sfix9 [90]
  SIGNAL RhoValueStart_out1               : vector_of_signed10(0 TO 89);  -- sfix10 [90]
  SIGNAL RhoValueStart_out1_1             : vector_of_signed9(0 TO 89);  -- sfix9 [90]
  SIGNAL X_2                              : signed(8 DOWNTO 0);  -- sfix9
  SIGNAL CosineCenter_out1                : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL CosineCenter_out1_1              : signed(15 DOWNTO 0);  -- sfix16_En14
  SIGNAL xcosCenter_out1                  : signed(24 DOWNTO 0);  -- sfix25_En14
  SIGNAL xcosCenter_out1_1                : signed(24 DOWNTO 0);  -- sfix25_En14
  SIGNAL xcosCenter_out1_2                : signed(8 DOWNTO 0);  -- sfix9
  SIGNAL ysin_90                          : signed(8 DOWNTO 0);  -- sfix9
  SIGNAL RhoValueCenter_out1              : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL RhoValueCenter_out1_1            : signed(8 DOWNTO 0);  -- sfix9
  SIGNAL Selector4_out1                   : vector_of_signed9(0 TO 88);  -- sfix9 [89]
  SIGNAL Selector1_out1                   : vector_of_signed9(0 TO 88);  -- sfix9 [89]
  SIGNAL RhoValueEnd_out1                 : vector_of_signed10(0 TO 88);  -- sfix10 [89]
  SIGNAL RhoValueEnd_out1_1               : vector_of_signed9(0 TO 88);  -- sfix9 [89]
  SIGNAL Matrix_Concatenate_out1          : vector_of_signed9(0 TO 179);  -- sfix9 [180]

BEGIN
  X_signed <= signed(X);

  HwModeRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      X_1 <= to_signed(16#000#, 9);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        X_1 <= X_signed;
      END IF;
    END IF;
  END PROCESS HwModeRegister_process;


  Cosine_out1(0) <= to_signed(16#4000#, 16);
  Cosine_out1(1) <= to_signed(16#3FFE#, 16);
  Cosine_out1(2) <= to_signed(16#3FF6#, 16);
  Cosine_out1(3) <= to_signed(16#3FEA#, 16);
  Cosine_out1(4) <= to_signed(16#3FD8#, 16);
  Cosine_out1(5) <= to_signed(16#3FC2#, 16);
  Cosine_out1(6) <= to_signed(16#3FA6#, 16);
  Cosine_out1(7) <= to_signed(16#3F86#, 16);
  Cosine_out1(8) <= to_signed(16#3F61#, 16);
  Cosine_out1(9) <= to_signed(16#3F36#, 16);
  Cosine_out1(10) <= to_signed(16#3F07#, 16);
  Cosine_out1(11) <= to_signed(16#3ED3#, 16);
  Cosine_out1(12) <= to_signed(16#3E9A#, 16);
  Cosine_out1(13) <= to_signed(16#3E5C#, 16);
  Cosine_out1(14) <= to_signed(16#3E19#, 16);
  Cosine_out1(15) <= to_signed(16#3DD2#, 16);
  Cosine_out1(16) <= to_signed(16#3D85#, 16);
  Cosine_out1(17) <= to_signed(16#3D34#, 16);
  Cosine_out1(18) <= to_signed(16#3CDE#, 16);
  Cosine_out1(19) <= to_signed(16#3C83#, 16);
  Cosine_out1(20) <= to_signed(16#3C24#, 16);
  Cosine_out1(21) <= to_signed(16#3BC0#, 16);
  Cosine_out1(22) <= to_signed(16#3B57#, 16);
  Cosine_out1(23) <= to_signed(16#3AEA#, 16);
  Cosine_out1(24) <= to_signed(16#3A78#, 16);
  Cosine_out1(25) <= to_signed(16#3A01#, 16);
  Cosine_out1(26) <= to_signed(16#3986#, 16);
  Cosine_out1(27) <= to_signed(16#3906#, 16);
  Cosine_out1(28) <= to_signed(16#3882#, 16);
  Cosine_out1(29) <= to_signed(16#37FA#, 16);
  Cosine_out1(30) <= to_signed(16#376D#, 16);
  Cosine_out1(31) <= to_signed(16#36DC#, 16);
  Cosine_out1(32) <= to_signed(16#3646#, 16);
  Cosine_out1(33) <= to_signed(16#35AD#, 16);
  Cosine_out1(34) <= to_signed(16#350F#, 16);
  Cosine_out1(35) <= to_signed(16#346D#, 16);
  Cosine_out1(36) <= to_signed(16#33C7#, 16);
  Cosine_out1(37) <= to_signed(16#331D#, 16);
  Cosine_out1(38) <= to_signed(16#326F#, 16);
  Cosine_out1(39) <= to_signed(16#31BD#, 16);
  Cosine_out1(40) <= to_signed(16#3107#, 16);
  Cosine_out1(41) <= to_signed(16#304D#, 16);
  Cosine_out1(42) <= to_signed(16#2F90#, 16);
  Cosine_out1(43) <= to_signed(16#2ECE#, 16);
  Cosine_out1(44) <= to_signed(16#2E0A#, 16);
  Cosine_out1(45) <= to_signed(16#2D41#, 16);
  Cosine_out1(46) <= to_signed(16#2C75#, 16);
  Cosine_out1(47) <= to_signed(16#2BA6#, 16);
  Cosine_out1(48) <= to_signed(16#2AD3#, 16);
  Cosine_out1(49) <= to_signed(16#29FD#, 16);
  Cosine_out1(50) <= to_signed(16#2923#, 16);
  Cosine_out1(51) <= to_signed(16#2847#, 16);
  Cosine_out1(52) <= to_signed(16#2767#, 16);
  Cosine_out1(53) <= to_signed(16#2684#, 16);
  Cosine_out1(54) <= to_signed(16#259E#, 16);
  Cosine_out1(55) <= to_signed(16#24B5#, 16);
  Cosine_out1(56) <= to_signed(16#23CA#, 16);
  Cosine_out1(57) <= to_signed(16#22DB#, 16);
  Cosine_out1(58) <= to_signed(16#21EA#, 16);
  Cosine_out1(59) <= to_signed(16#20F6#, 16);
  Cosine_out1(60) <= to_signed(16#2000#, 16);
  Cosine_out1(61) <= to_signed(16#1F07#, 16);
  Cosine_out1(62) <= to_signed(16#1E0C#, 16);
  Cosine_out1(63) <= to_signed(16#1D0E#, 16);
  Cosine_out1(64) <= to_signed(16#1C0E#, 16);
  Cosine_out1(65) <= to_signed(16#1B0C#, 16);
  Cosine_out1(66) <= to_signed(16#1A08#, 16);
  Cosine_out1(67) <= to_signed(16#1902#, 16);
  Cosine_out1(68) <= to_signed(16#17FA#, 16);
  Cosine_out1(69) <= to_signed(16#16F0#, 16);
  Cosine_out1(70) <= to_signed(16#15E4#, 16);
  Cosine_out1(71) <= to_signed(16#14D6#, 16);
  Cosine_out1(72) <= to_signed(16#13C7#, 16);
  Cosine_out1(73) <= to_signed(16#12B6#, 16);
  Cosine_out1(74) <= to_signed(16#11A4#, 16);
  Cosine_out1(75) <= to_signed(16#1090#, 16);
  Cosine_out1(76) <= to_signed(16#0F7C#, 16);
  Cosine_out1(77) <= to_signed(16#0E66#, 16);
  Cosine_out1(78) <= to_signed(16#0D4E#, 16);
  Cosine_out1(79) <= to_signed(16#0C36#, 16);
  Cosine_out1(80) <= to_signed(16#0B1D#, 16);
  Cosine_out1(81) <= to_signed(16#0A03#, 16);
  Cosine_out1(82) <= to_signed(16#08E8#, 16);
  Cosine_out1(83) <= to_signed(16#07CD#, 16);
  Cosine_out1(84) <= to_signed(16#06B1#, 16);
  Cosine_out1(85) <= to_signed(16#0594#, 16);
  Cosine_out1(86) <= to_signed(16#0477#, 16);
  Cosine_out1(87) <= to_signed(16#0359#, 16);
  Cosine_out1(88) <= to_signed(16#023C#, 16);
  Cosine_out1(89) <= to_signed(16#011E#, 16);

  HwModeRegister1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Cosine_out1_1 <= (OTHERS => to_signed(16#0000#, 16));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Cosine_out1_1 <= Cosine_out1;
      END IF;
    END IF;
  END PROCESS HwModeRegister1_process;



  xcos_out1_gen: FOR t_0 IN 0 TO 89 GENERATE
    xcos_out1(t_0) <= X_1 * Cosine_out1_1(t_0);
  END GENERATE xcos_out1_gen;


  PipelineRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xcos_out1_1 <= (OTHERS => to_signed(16#0000000#, 25));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xcos_out1_1 <= xcos_out1;
      END IF;
    END IF;
  END PROCESS PipelineRegister_process;



  xcos_out1_2_gen: FOR ii IN 0 TO 89 GENERATE
    xcos_out1_2(ii) <= xcos_out1_1(ii)(22 DOWNTO 14) + ('0' & (xcos_out1_1(ii)(13) AND (( NOT xcos_out1_1(ii)(24)) OR (xcos_out1_1(ii)(12) OR xcos_out1_1(ii)(11) OR xcos_out1_1(ii)(10) OR xcos_out1_1(ii)(9) OR xcos_out1_1(ii)(8) OR xcos_out1_1(ii)(7) OR xcos_out1_1(ii)(6) OR xcos_out1_1(ii)(5) OR xcos_out1_1(ii)(4) OR xcos_out1_1(ii)(3) OR xcos_out1_1(ii)(2) OR xcos_out1_1(ii)(1) OR xcos_out1_1(ii)(0)))));
  END GENERATE xcos_out1_2_gen;


  Selector_out1(0) <= signed(ysin(0));
  Selector_out1(1) <= signed(ysin(1));
  Selector_out1(2) <= signed(ysin(2));
  Selector_out1(3) <= signed(ysin(3));
  Selector_out1(4) <= signed(ysin(4));
  Selector_out1(5) <= signed(ysin(5));
  Selector_out1(6) <= signed(ysin(6));
  Selector_out1(7) <= signed(ysin(7));
  Selector_out1(8) <= signed(ysin(8));
  Selector_out1(9) <= signed(ysin(9));
  Selector_out1(10) <= signed(ysin(10));
  Selector_out1(11) <= signed(ysin(11));
  Selector_out1(12) <= signed(ysin(12));
  Selector_out1(13) <= signed(ysin(13));
  Selector_out1(14) <= signed(ysin(14));
  Selector_out1(15) <= signed(ysin(15));
  Selector_out1(16) <= signed(ysin(16));
  Selector_out1(17) <= signed(ysin(17));
  Selector_out1(18) <= signed(ysin(18));
  Selector_out1(19) <= signed(ysin(19));
  Selector_out1(20) <= signed(ysin(20));
  Selector_out1(21) <= signed(ysin(21));
  Selector_out1(22) <= signed(ysin(22));
  Selector_out1(23) <= signed(ysin(23));
  Selector_out1(24) <= signed(ysin(24));
  Selector_out1(25) <= signed(ysin(25));
  Selector_out1(26) <= signed(ysin(26));
  Selector_out1(27) <= signed(ysin(27));
  Selector_out1(28) <= signed(ysin(28));
  Selector_out1(29) <= signed(ysin(29));
  Selector_out1(30) <= signed(ysin(30));
  Selector_out1(31) <= signed(ysin(31));
  Selector_out1(32) <= signed(ysin(32));
  Selector_out1(33) <= signed(ysin(33));
  Selector_out1(34) <= signed(ysin(34));
  Selector_out1(35) <= signed(ysin(35));
  Selector_out1(36) <= signed(ysin(36));
  Selector_out1(37) <= signed(ysin(37));
  Selector_out1(38) <= signed(ysin(38));
  Selector_out1(39) <= signed(ysin(39));
  Selector_out1(40) <= signed(ysin(40));
  Selector_out1(41) <= signed(ysin(41));
  Selector_out1(42) <= signed(ysin(42));
  Selector_out1(43) <= signed(ysin(43));
  Selector_out1(44) <= signed(ysin(44));
  Selector_out1(45) <= signed(ysin(45));
  Selector_out1(46) <= signed(ysin(46));
  Selector_out1(47) <= signed(ysin(47));
  Selector_out1(48) <= signed(ysin(48));
  Selector_out1(49) <= signed(ysin(49));
  Selector_out1(50) <= signed(ysin(50));
  Selector_out1(51) <= signed(ysin(51));
  Selector_out1(52) <= signed(ysin(52));
  Selector_out1(53) <= signed(ysin(53));
  Selector_out1(54) <= signed(ysin(54));
  Selector_out1(55) <= signed(ysin(55));
  Selector_out1(56) <= signed(ysin(56));
  Selector_out1(57) <= signed(ysin(57));
  Selector_out1(58) <= signed(ysin(58));
  Selector_out1(59) <= signed(ysin(59));
  Selector_out1(60) <= signed(ysin(60));
  Selector_out1(61) <= signed(ysin(61));
  Selector_out1(62) <= signed(ysin(62));
  Selector_out1(63) <= signed(ysin(63));
  Selector_out1(64) <= signed(ysin(64));
  Selector_out1(65) <= signed(ysin(65));
  Selector_out1(66) <= signed(ysin(66));
  Selector_out1(67) <= signed(ysin(67));
  Selector_out1(68) <= signed(ysin(68));
  Selector_out1(69) <= signed(ysin(69));
  Selector_out1(70) <= signed(ysin(70));
  Selector_out1(71) <= signed(ysin(71));
  Selector_out1(72) <= signed(ysin(72));
  Selector_out1(73) <= signed(ysin(73));
  Selector_out1(74) <= signed(ysin(74));
  Selector_out1(75) <= signed(ysin(75));
  Selector_out1(76) <= signed(ysin(76));
  Selector_out1(77) <= signed(ysin(77));
  Selector_out1(78) <= signed(ysin(78));
  Selector_out1(79) <= signed(ysin(79));
  Selector_out1(80) <= signed(ysin(80));
  Selector_out1(81) <= signed(ysin(81));
  Selector_out1(82) <= signed(ysin(82));
  Selector_out1(83) <= signed(ysin(83));
  Selector_out1(84) <= signed(ysin(84));
  Selector_out1(85) <= signed(ysin(85));
  Selector_out1(86) <= signed(ysin(86));
  Selector_out1(87) <= signed(ysin(87));
  Selector_out1(88) <= signed(ysin(88));
  Selector_out1(89) <= signed(ysin(89));


  RhoValueStart_out1_gen: FOR t_01 IN 0 TO 89 GENERATE
    RhoValueStart_out1(t_01) <= resize(xcos_out1_2(t_01), 10) + resize(Selector_out1(t_01), 10);
  END GENERATE RhoValueStart_out1_gen;



  RhoValueStart_out1_1_gen: FOR ii1 IN 0 TO 89 GENERATE
    RhoValueStart_out1_1(ii1) <= RhoValueStart_out1(ii1)(8 DOWNTO 0);
  END GENERATE RhoValueStart_out1_1_gen;


  HwModeRegister2_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      X_2 <= to_signed(16#000#, 9);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        X_2 <= X_signed;
      END IF;
    END IF;
  END PROCESS HwModeRegister2_process;


  CosineCenter_out1 <= to_signed(16#0000#, 16);

  HwModeRegister3_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      CosineCenter_out1_1 <= to_signed(16#0000#, 16);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        CosineCenter_out1_1 <= CosineCenter_out1;
      END IF;
    END IF;
  END PROCESS HwModeRegister3_process;


  xcosCenter_out1 <= X_2 * CosineCenter_out1_1;

  PipelineRegister1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      xcosCenter_out1_1 <= to_signed(16#0000000#, 25);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        xcosCenter_out1_1 <= xcosCenter_out1;
      END IF;
    END IF;
  END PROCESS PipelineRegister1_process;


  xcosCenter_out1_2 <= xcosCenter_out1_1(22 DOWNTO 14) + ('0' & (xcosCenter_out1_1(13) AND (( NOT xcosCenter_out1_1(24)) OR (xcosCenter_out1_1(12) OR xcosCenter_out1_1(11) OR xcosCenter_out1_1(10) OR xcosCenter_out1_1(9) OR xcosCenter_out1_1(8) OR xcosCenter_out1_1(7) OR xcosCenter_out1_1(6) OR xcosCenter_out1_1(5) OR xcosCenter_out1_1(4) OR xcosCenter_out1_1(3) OR xcosCenter_out1_1(2) OR xcosCenter_out1_1(1) OR xcosCenter_out1_1(0)))));

  ysin_90 <= signed(ysin(90));

  RhoValueCenter_out1 <= resize(xcosCenter_out1_2, 10) + resize(ysin_90, 10);

  RhoValueCenter_out1_1 <= RhoValueCenter_out1(8 DOWNTO 0);

  Selector4_out1(0) <= signed(ysin(89));
  Selector4_out1(1) <= signed(ysin(88));
  Selector4_out1(2) <= signed(ysin(87));
  Selector4_out1(3) <= signed(ysin(86));
  Selector4_out1(4) <= signed(ysin(85));
  Selector4_out1(5) <= signed(ysin(84));
  Selector4_out1(6) <= signed(ysin(83));
  Selector4_out1(7) <= signed(ysin(82));
  Selector4_out1(8) <= signed(ysin(81));
  Selector4_out1(9) <= signed(ysin(80));
  Selector4_out1(10) <= signed(ysin(79));
  Selector4_out1(11) <= signed(ysin(78));
  Selector4_out1(12) <= signed(ysin(77));
  Selector4_out1(13) <= signed(ysin(76));
  Selector4_out1(14) <= signed(ysin(75));
  Selector4_out1(15) <= signed(ysin(74));
  Selector4_out1(16) <= signed(ysin(73));
  Selector4_out1(17) <= signed(ysin(72));
  Selector4_out1(18) <= signed(ysin(71));
  Selector4_out1(19) <= signed(ysin(70));
  Selector4_out1(20) <= signed(ysin(69));
  Selector4_out1(21) <= signed(ysin(68));
  Selector4_out1(22) <= signed(ysin(67));
  Selector4_out1(23) <= signed(ysin(66));
  Selector4_out1(24) <= signed(ysin(65));
  Selector4_out1(25) <= signed(ysin(64));
  Selector4_out1(26) <= signed(ysin(63));
  Selector4_out1(27) <= signed(ysin(62));
  Selector4_out1(28) <= signed(ysin(61));
  Selector4_out1(29) <= signed(ysin(60));
  Selector4_out1(30) <= signed(ysin(59));
  Selector4_out1(31) <= signed(ysin(58));
  Selector4_out1(32) <= signed(ysin(57));
  Selector4_out1(33) <= signed(ysin(56));
  Selector4_out1(34) <= signed(ysin(55));
  Selector4_out1(35) <= signed(ysin(54));
  Selector4_out1(36) <= signed(ysin(53));
  Selector4_out1(37) <= signed(ysin(52));
  Selector4_out1(38) <= signed(ysin(51));
  Selector4_out1(39) <= signed(ysin(50));
  Selector4_out1(40) <= signed(ysin(49));
  Selector4_out1(41) <= signed(ysin(48));
  Selector4_out1(42) <= signed(ysin(47));
  Selector4_out1(43) <= signed(ysin(46));
  Selector4_out1(44) <= signed(ysin(45));
  Selector4_out1(45) <= signed(ysin(44));
  Selector4_out1(46) <= signed(ysin(43));
  Selector4_out1(47) <= signed(ysin(42));
  Selector4_out1(48) <= signed(ysin(41));
  Selector4_out1(49) <= signed(ysin(40));
  Selector4_out1(50) <= signed(ysin(39));
  Selector4_out1(51) <= signed(ysin(38));
  Selector4_out1(52) <= signed(ysin(37));
  Selector4_out1(53) <= signed(ysin(36));
  Selector4_out1(54) <= signed(ysin(35));
  Selector4_out1(55) <= signed(ysin(34));
  Selector4_out1(56) <= signed(ysin(33));
  Selector4_out1(57) <= signed(ysin(32));
  Selector4_out1(58) <= signed(ysin(31));
  Selector4_out1(59) <= signed(ysin(30));
  Selector4_out1(60) <= signed(ysin(29));
  Selector4_out1(61) <= signed(ysin(28));
  Selector4_out1(62) <= signed(ysin(27));
  Selector4_out1(63) <= signed(ysin(26));
  Selector4_out1(64) <= signed(ysin(25));
  Selector4_out1(65) <= signed(ysin(24));
  Selector4_out1(66) <= signed(ysin(23));
  Selector4_out1(67) <= signed(ysin(22));
  Selector4_out1(68) <= signed(ysin(21));
  Selector4_out1(69) <= signed(ysin(20));
  Selector4_out1(70) <= signed(ysin(19));
  Selector4_out1(71) <= signed(ysin(18));
  Selector4_out1(72) <= signed(ysin(17));
  Selector4_out1(73) <= signed(ysin(16));
  Selector4_out1(74) <= signed(ysin(15));
  Selector4_out1(75) <= signed(ysin(14));
  Selector4_out1(76) <= signed(ysin(13));
  Selector4_out1(77) <= signed(ysin(12));
  Selector4_out1(78) <= signed(ysin(11));
  Selector4_out1(79) <= signed(ysin(10));
  Selector4_out1(80) <= signed(ysin(9));
  Selector4_out1(81) <= signed(ysin(8));
  Selector4_out1(82) <= signed(ysin(7));
  Selector4_out1(83) <= signed(ysin(6));
  Selector4_out1(84) <= signed(ysin(5));
  Selector4_out1(85) <= signed(ysin(4));
  Selector4_out1(86) <= signed(ysin(3));
  Selector4_out1(87) <= signed(ysin(2));
  Selector4_out1(88) <= signed(ysin(1));

  Selector1_out1(0) <= xcos_out1_2(89);
  Selector1_out1(1) <= xcos_out1_2(88);
  Selector1_out1(2) <= xcos_out1_2(87);
  Selector1_out1(3) <= xcos_out1_2(86);
  Selector1_out1(4) <= xcos_out1_2(85);
  Selector1_out1(5) <= xcos_out1_2(84);
  Selector1_out1(6) <= xcos_out1_2(83);
  Selector1_out1(7) <= xcos_out1_2(82);
  Selector1_out1(8) <= xcos_out1_2(81);
  Selector1_out1(9) <= xcos_out1_2(80);
  Selector1_out1(10) <= xcos_out1_2(79);
  Selector1_out1(11) <= xcos_out1_2(78);
  Selector1_out1(12) <= xcos_out1_2(77);
  Selector1_out1(13) <= xcos_out1_2(76);
  Selector1_out1(14) <= xcos_out1_2(75);
  Selector1_out1(15) <= xcos_out1_2(74);
  Selector1_out1(16) <= xcos_out1_2(73);
  Selector1_out1(17) <= xcos_out1_2(72);
  Selector1_out1(18) <= xcos_out1_2(71);
  Selector1_out1(19) <= xcos_out1_2(70);
  Selector1_out1(20) <= xcos_out1_2(69);
  Selector1_out1(21) <= xcos_out1_2(68);
  Selector1_out1(22) <= xcos_out1_2(67);
  Selector1_out1(23) <= xcos_out1_2(66);
  Selector1_out1(24) <= xcos_out1_2(65);
  Selector1_out1(25) <= xcos_out1_2(64);
  Selector1_out1(26) <= xcos_out1_2(63);
  Selector1_out1(27) <= xcos_out1_2(62);
  Selector1_out1(28) <= xcos_out1_2(61);
  Selector1_out1(29) <= xcos_out1_2(60);
  Selector1_out1(30) <= xcos_out1_2(59);
  Selector1_out1(31) <= xcos_out1_2(58);
  Selector1_out1(32) <= xcos_out1_2(57);
  Selector1_out1(33) <= xcos_out1_2(56);
  Selector1_out1(34) <= xcos_out1_2(55);
  Selector1_out1(35) <= xcos_out1_2(54);
  Selector1_out1(36) <= xcos_out1_2(53);
  Selector1_out1(37) <= xcos_out1_2(52);
  Selector1_out1(38) <= xcos_out1_2(51);
  Selector1_out1(39) <= xcos_out1_2(50);
  Selector1_out1(40) <= xcos_out1_2(49);
  Selector1_out1(41) <= xcos_out1_2(48);
  Selector1_out1(42) <= xcos_out1_2(47);
  Selector1_out1(43) <= xcos_out1_2(46);
  Selector1_out1(44) <= xcos_out1_2(45);
  Selector1_out1(45) <= xcos_out1_2(44);
  Selector1_out1(46) <= xcos_out1_2(43);
  Selector1_out1(47) <= xcos_out1_2(42);
  Selector1_out1(48) <= xcos_out1_2(41);
  Selector1_out1(49) <= xcos_out1_2(40);
  Selector1_out1(50) <= xcos_out1_2(39);
  Selector1_out1(51) <= xcos_out1_2(38);
  Selector1_out1(52) <= xcos_out1_2(37);
  Selector1_out1(53) <= xcos_out1_2(36);
  Selector1_out1(54) <= xcos_out1_2(35);
  Selector1_out1(55) <= xcos_out1_2(34);
  Selector1_out1(56) <= xcos_out1_2(33);
  Selector1_out1(57) <= xcos_out1_2(32);
  Selector1_out1(58) <= xcos_out1_2(31);
  Selector1_out1(59) <= xcos_out1_2(30);
  Selector1_out1(60) <= xcos_out1_2(29);
  Selector1_out1(61) <= xcos_out1_2(28);
  Selector1_out1(62) <= xcos_out1_2(27);
  Selector1_out1(63) <= xcos_out1_2(26);
  Selector1_out1(64) <= xcos_out1_2(25);
  Selector1_out1(65) <= xcos_out1_2(24);
  Selector1_out1(66) <= xcos_out1_2(23);
  Selector1_out1(67) <= xcos_out1_2(22);
  Selector1_out1(68) <= xcos_out1_2(21);
  Selector1_out1(69) <= xcos_out1_2(20);
  Selector1_out1(70) <= xcos_out1_2(19);
  Selector1_out1(71) <= xcos_out1_2(18);
  Selector1_out1(72) <= xcos_out1_2(17);
  Selector1_out1(73) <= xcos_out1_2(16);
  Selector1_out1(74) <= xcos_out1_2(15);
  Selector1_out1(75) <= xcos_out1_2(14);
  Selector1_out1(76) <= xcos_out1_2(13);
  Selector1_out1(77) <= xcos_out1_2(12);
  Selector1_out1(78) <= xcos_out1_2(11);
  Selector1_out1(79) <= xcos_out1_2(10);
  Selector1_out1(80) <= xcos_out1_2(9);
  Selector1_out1(81) <= xcos_out1_2(8);
  Selector1_out1(82) <= xcos_out1_2(7);
  Selector1_out1(83) <= xcos_out1_2(6);
  Selector1_out1(84) <= xcos_out1_2(5);
  Selector1_out1(85) <= xcos_out1_2(4);
  Selector1_out1(86) <= xcos_out1_2(3);
  Selector1_out1(87) <= xcos_out1_2(2);
  Selector1_out1(88) <= xcos_out1_2(1);


  RhoValueEnd_out1_gen: FOR t_02 IN 0 TO 88 GENERATE
    RhoValueEnd_out1(t_02) <= resize(Selector4_out1(t_02), 10) - resize(Selector1_out1(t_02), 10);
  END GENERATE RhoValueEnd_out1_gen;



  RhoValueEnd_out1_1_gen: FOR ii2 IN 0 TO 88 GENERATE
    RhoValueEnd_out1_1(ii2) <= RhoValueEnd_out1(ii2)(8 DOWNTO 0);
  END GENERATE RhoValueEnd_out1_1_gen;


  Matrix_Concatenate_out1(0) <= RhoValueStart_out1_1(0);
  Matrix_Concatenate_out1(1) <= RhoValueStart_out1_1(1);
  Matrix_Concatenate_out1(2) <= RhoValueStart_out1_1(2);
  Matrix_Concatenate_out1(3) <= RhoValueStart_out1_1(3);
  Matrix_Concatenate_out1(4) <= RhoValueStart_out1_1(4);
  Matrix_Concatenate_out1(5) <= RhoValueStart_out1_1(5);
  Matrix_Concatenate_out1(6) <= RhoValueStart_out1_1(6);
  Matrix_Concatenate_out1(7) <= RhoValueStart_out1_1(7);
  Matrix_Concatenate_out1(8) <= RhoValueStart_out1_1(8);
  Matrix_Concatenate_out1(9) <= RhoValueStart_out1_1(9);
  Matrix_Concatenate_out1(10) <= RhoValueStart_out1_1(10);
  Matrix_Concatenate_out1(11) <= RhoValueStart_out1_1(11);
  Matrix_Concatenate_out1(12) <= RhoValueStart_out1_1(12);
  Matrix_Concatenate_out1(13) <= RhoValueStart_out1_1(13);
  Matrix_Concatenate_out1(14) <= RhoValueStart_out1_1(14);
  Matrix_Concatenate_out1(15) <= RhoValueStart_out1_1(15);
  Matrix_Concatenate_out1(16) <= RhoValueStart_out1_1(16);
  Matrix_Concatenate_out1(17) <= RhoValueStart_out1_1(17);
  Matrix_Concatenate_out1(18) <= RhoValueStart_out1_1(18);
  Matrix_Concatenate_out1(19) <= RhoValueStart_out1_1(19);
  Matrix_Concatenate_out1(20) <= RhoValueStart_out1_1(20);
  Matrix_Concatenate_out1(21) <= RhoValueStart_out1_1(21);
  Matrix_Concatenate_out1(22) <= RhoValueStart_out1_1(22);
  Matrix_Concatenate_out1(23) <= RhoValueStart_out1_1(23);
  Matrix_Concatenate_out1(24) <= RhoValueStart_out1_1(24);
  Matrix_Concatenate_out1(25) <= RhoValueStart_out1_1(25);
  Matrix_Concatenate_out1(26) <= RhoValueStart_out1_1(26);
  Matrix_Concatenate_out1(27) <= RhoValueStart_out1_1(27);
  Matrix_Concatenate_out1(28) <= RhoValueStart_out1_1(28);
  Matrix_Concatenate_out1(29) <= RhoValueStart_out1_1(29);
  Matrix_Concatenate_out1(30) <= RhoValueStart_out1_1(30);
  Matrix_Concatenate_out1(31) <= RhoValueStart_out1_1(31);
  Matrix_Concatenate_out1(32) <= RhoValueStart_out1_1(32);
  Matrix_Concatenate_out1(33) <= RhoValueStart_out1_1(33);
  Matrix_Concatenate_out1(34) <= RhoValueStart_out1_1(34);
  Matrix_Concatenate_out1(35) <= RhoValueStart_out1_1(35);
  Matrix_Concatenate_out1(36) <= RhoValueStart_out1_1(36);
  Matrix_Concatenate_out1(37) <= RhoValueStart_out1_1(37);
  Matrix_Concatenate_out1(38) <= RhoValueStart_out1_1(38);
  Matrix_Concatenate_out1(39) <= RhoValueStart_out1_1(39);
  Matrix_Concatenate_out1(40) <= RhoValueStart_out1_1(40);
  Matrix_Concatenate_out1(41) <= RhoValueStart_out1_1(41);
  Matrix_Concatenate_out1(42) <= RhoValueStart_out1_1(42);
  Matrix_Concatenate_out1(43) <= RhoValueStart_out1_1(43);
  Matrix_Concatenate_out1(44) <= RhoValueStart_out1_1(44);
  Matrix_Concatenate_out1(45) <= RhoValueStart_out1_1(45);
  Matrix_Concatenate_out1(46) <= RhoValueStart_out1_1(46);
  Matrix_Concatenate_out1(47) <= RhoValueStart_out1_1(47);
  Matrix_Concatenate_out1(48) <= RhoValueStart_out1_1(48);
  Matrix_Concatenate_out1(49) <= RhoValueStart_out1_1(49);
  Matrix_Concatenate_out1(50) <= RhoValueStart_out1_1(50);
  Matrix_Concatenate_out1(51) <= RhoValueStart_out1_1(51);
  Matrix_Concatenate_out1(52) <= RhoValueStart_out1_1(52);
  Matrix_Concatenate_out1(53) <= RhoValueStart_out1_1(53);
  Matrix_Concatenate_out1(54) <= RhoValueStart_out1_1(54);
  Matrix_Concatenate_out1(55) <= RhoValueStart_out1_1(55);
  Matrix_Concatenate_out1(56) <= RhoValueStart_out1_1(56);
  Matrix_Concatenate_out1(57) <= RhoValueStart_out1_1(57);
  Matrix_Concatenate_out1(58) <= RhoValueStart_out1_1(58);
  Matrix_Concatenate_out1(59) <= RhoValueStart_out1_1(59);
  Matrix_Concatenate_out1(60) <= RhoValueStart_out1_1(60);
  Matrix_Concatenate_out1(61) <= RhoValueStart_out1_1(61);
  Matrix_Concatenate_out1(62) <= RhoValueStart_out1_1(62);
  Matrix_Concatenate_out1(63) <= RhoValueStart_out1_1(63);
  Matrix_Concatenate_out1(64) <= RhoValueStart_out1_1(64);
  Matrix_Concatenate_out1(65) <= RhoValueStart_out1_1(65);
  Matrix_Concatenate_out1(66) <= RhoValueStart_out1_1(66);
  Matrix_Concatenate_out1(67) <= RhoValueStart_out1_1(67);
  Matrix_Concatenate_out1(68) <= RhoValueStart_out1_1(68);
  Matrix_Concatenate_out1(69) <= RhoValueStart_out1_1(69);
  Matrix_Concatenate_out1(70) <= RhoValueStart_out1_1(70);
  Matrix_Concatenate_out1(71) <= RhoValueStart_out1_1(71);
  Matrix_Concatenate_out1(72) <= RhoValueStart_out1_1(72);
  Matrix_Concatenate_out1(73) <= RhoValueStart_out1_1(73);
  Matrix_Concatenate_out1(74) <= RhoValueStart_out1_1(74);
  Matrix_Concatenate_out1(75) <= RhoValueStart_out1_1(75);
  Matrix_Concatenate_out1(76) <= RhoValueStart_out1_1(76);
  Matrix_Concatenate_out1(77) <= RhoValueStart_out1_1(77);
  Matrix_Concatenate_out1(78) <= RhoValueStart_out1_1(78);
  Matrix_Concatenate_out1(79) <= RhoValueStart_out1_1(79);
  Matrix_Concatenate_out1(80) <= RhoValueStart_out1_1(80);
  Matrix_Concatenate_out1(81) <= RhoValueStart_out1_1(81);
  Matrix_Concatenate_out1(82) <= RhoValueStart_out1_1(82);
  Matrix_Concatenate_out1(83) <= RhoValueStart_out1_1(83);
  Matrix_Concatenate_out1(84) <= RhoValueStart_out1_1(84);
  Matrix_Concatenate_out1(85) <= RhoValueStart_out1_1(85);
  Matrix_Concatenate_out1(86) <= RhoValueStart_out1_1(86);
  Matrix_Concatenate_out1(87) <= RhoValueStart_out1_1(87);
  Matrix_Concatenate_out1(88) <= RhoValueStart_out1_1(88);
  Matrix_Concatenate_out1(89) <= RhoValueStart_out1_1(89);
  Matrix_Concatenate_out1(90) <= RhoValueCenter_out1_1;
  Matrix_Concatenate_out1(91) <= RhoValueEnd_out1_1(0);
  Matrix_Concatenate_out1(92) <= RhoValueEnd_out1_1(1);
  Matrix_Concatenate_out1(93) <= RhoValueEnd_out1_1(2);
  Matrix_Concatenate_out1(94) <= RhoValueEnd_out1_1(3);
  Matrix_Concatenate_out1(95) <= RhoValueEnd_out1_1(4);
  Matrix_Concatenate_out1(96) <= RhoValueEnd_out1_1(5);
  Matrix_Concatenate_out1(97) <= RhoValueEnd_out1_1(6);
  Matrix_Concatenate_out1(98) <= RhoValueEnd_out1_1(7);
  Matrix_Concatenate_out1(99) <= RhoValueEnd_out1_1(8);
  Matrix_Concatenate_out1(100) <= RhoValueEnd_out1_1(9);
  Matrix_Concatenate_out1(101) <= RhoValueEnd_out1_1(10);
  Matrix_Concatenate_out1(102) <= RhoValueEnd_out1_1(11);
  Matrix_Concatenate_out1(103) <= RhoValueEnd_out1_1(12);
  Matrix_Concatenate_out1(104) <= RhoValueEnd_out1_1(13);
  Matrix_Concatenate_out1(105) <= RhoValueEnd_out1_1(14);
  Matrix_Concatenate_out1(106) <= RhoValueEnd_out1_1(15);
  Matrix_Concatenate_out1(107) <= RhoValueEnd_out1_1(16);
  Matrix_Concatenate_out1(108) <= RhoValueEnd_out1_1(17);
  Matrix_Concatenate_out1(109) <= RhoValueEnd_out1_1(18);
  Matrix_Concatenate_out1(110) <= RhoValueEnd_out1_1(19);
  Matrix_Concatenate_out1(111) <= RhoValueEnd_out1_1(20);
  Matrix_Concatenate_out1(112) <= RhoValueEnd_out1_1(21);
  Matrix_Concatenate_out1(113) <= RhoValueEnd_out1_1(22);
  Matrix_Concatenate_out1(114) <= RhoValueEnd_out1_1(23);
  Matrix_Concatenate_out1(115) <= RhoValueEnd_out1_1(24);
  Matrix_Concatenate_out1(116) <= RhoValueEnd_out1_1(25);
  Matrix_Concatenate_out1(117) <= RhoValueEnd_out1_1(26);
  Matrix_Concatenate_out1(118) <= RhoValueEnd_out1_1(27);
  Matrix_Concatenate_out1(119) <= RhoValueEnd_out1_1(28);
  Matrix_Concatenate_out1(120) <= RhoValueEnd_out1_1(29);
  Matrix_Concatenate_out1(121) <= RhoValueEnd_out1_1(30);
  Matrix_Concatenate_out1(122) <= RhoValueEnd_out1_1(31);
  Matrix_Concatenate_out1(123) <= RhoValueEnd_out1_1(32);
  Matrix_Concatenate_out1(124) <= RhoValueEnd_out1_1(33);
  Matrix_Concatenate_out1(125) <= RhoValueEnd_out1_1(34);
  Matrix_Concatenate_out1(126) <= RhoValueEnd_out1_1(35);
  Matrix_Concatenate_out1(127) <= RhoValueEnd_out1_1(36);
  Matrix_Concatenate_out1(128) <= RhoValueEnd_out1_1(37);
  Matrix_Concatenate_out1(129) <= RhoValueEnd_out1_1(38);
  Matrix_Concatenate_out1(130) <= RhoValueEnd_out1_1(39);
  Matrix_Concatenate_out1(131) <= RhoValueEnd_out1_1(40);
  Matrix_Concatenate_out1(132) <= RhoValueEnd_out1_1(41);
  Matrix_Concatenate_out1(133) <= RhoValueEnd_out1_1(42);
  Matrix_Concatenate_out1(134) <= RhoValueEnd_out1_1(43);
  Matrix_Concatenate_out1(135) <= RhoValueEnd_out1_1(44);
  Matrix_Concatenate_out1(136) <= RhoValueEnd_out1_1(45);
  Matrix_Concatenate_out1(137) <= RhoValueEnd_out1_1(46);
  Matrix_Concatenate_out1(138) <= RhoValueEnd_out1_1(47);
  Matrix_Concatenate_out1(139) <= RhoValueEnd_out1_1(48);
  Matrix_Concatenate_out1(140) <= RhoValueEnd_out1_1(49);
  Matrix_Concatenate_out1(141) <= RhoValueEnd_out1_1(50);
  Matrix_Concatenate_out1(142) <= RhoValueEnd_out1_1(51);
  Matrix_Concatenate_out1(143) <= RhoValueEnd_out1_1(52);
  Matrix_Concatenate_out1(144) <= RhoValueEnd_out1_1(53);
  Matrix_Concatenate_out1(145) <= RhoValueEnd_out1_1(54);
  Matrix_Concatenate_out1(146) <= RhoValueEnd_out1_1(55);
  Matrix_Concatenate_out1(147) <= RhoValueEnd_out1_1(56);
  Matrix_Concatenate_out1(148) <= RhoValueEnd_out1_1(57);
  Matrix_Concatenate_out1(149) <= RhoValueEnd_out1_1(58);
  Matrix_Concatenate_out1(150) <= RhoValueEnd_out1_1(59);
  Matrix_Concatenate_out1(151) <= RhoValueEnd_out1_1(60);
  Matrix_Concatenate_out1(152) <= RhoValueEnd_out1_1(61);
  Matrix_Concatenate_out1(153) <= RhoValueEnd_out1_1(62);
  Matrix_Concatenate_out1(154) <= RhoValueEnd_out1_1(63);
  Matrix_Concatenate_out1(155) <= RhoValueEnd_out1_1(64);
  Matrix_Concatenate_out1(156) <= RhoValueEnd_out1_1(65);
  Matrix_Concatenate_out1(157) <= RhoValueEnd_out1_1(66);
  Matrix_Concatenate_out1(158) <= RhoValueEnd_out1_1(67);
  Matrix_Concatenate_out1(159) <= RhoValueEnd_out1_1(68);
  Matrix_Concatenate_out1(160) <= RhoValueEnd_out1_1(69);
  Matrix_Concatenate_out1(161) <= RhoValueEnd_out1_1(70);
  Matrix_Concatenate_out1(162) <= RhoValueEnd_out1_1(71);
  Matrix_Concatenate_out1(163) <= RhoValueEnd_out1_1(72);
  Matrix_Concatenate_out1(164) <= RhoValueEnd_out1_1(73);
  Matrix_Concatenate_out1(165) <= RhoValueEnd_out1_1(74);
  Matrix_Concatenate_out1(166) <= RhoValueEnd_out1_1(75);
  Matrix_Concatenate_out1(167) <= RhoValueEnd_out1_1(76);
  Matrix_Concatenate_out1(168) <= RhoValueEnd_out1_1(77);
  Matrix_Concatenate_out1(169) <= RhoValueEnd_out1_1(78);
  Matrix_Concatenate_out1(170) <= RhoValueEnd_out1_1(79);
  Matrix_Concatenate_out1(171) <= RhoValueEnd_out1_1(80);
  Matrix_Concatenate_out1(172) <= RhoValueEnd_out1_1(81);
  Matrix_Concatenate_out1(173) <= RhoValueEnd_out1_1(82);
  Matrix_Concatenate_out1(174) <= RhoValueEnd_out1_1(83);
  Matrix_Concatenate_out1(175) <= RhoValueEnd_out1_1(84);
  Matrix_Concatenate_out1(176) <= RhoValueEnd_out1_1(85);
  Matrix_Concatenate_out1(177) <= RhoValueEnd_out1_1(86);
  Matrix_Concatenate_out1(178) <= RhoValueEnd_out1_1(87);
  Matrix_Concatenate_out1(179) <= RhoValueEnd_out1_1(88);

  outputgen: FOR k IN 0 TO 179 GENERATE
    Rho(k) <= std_logic_vector(Matrix_Concatenate_out1(k));
  END GENERATE;

END rtl;

