vlib work
vcom  Hybrid_LHT_pkg.vhd
vcom  SimpleDualPortRAM_generic.vhd
vcom  Simple_Dual_Port_RAM_Generator.vhd
vcom  Block_RAM.vhd
vcom  Accumulator.vhd
vcom  Accumulator_with_Switches.vhd
vcom  Accumulator_Controller.vhd
vcom  Hybrid_LHT_Accumulator.vhd
vcom  GetShift.vhd
vcom  Extract_Active_Votes.vhd
vcom  Extract_Active_Votes_block.vhd
vcom  GetShift1.vhd
vcom  Get_Index_and_Fix_Limits.vhd
vcom  Hough_Kernel.vhd
vcom  MATLAB_Function.vhd
vcom  Register_Bank.vhd
vcom  Look_Ahead_Hough_Symmetric.vhd
vcom  Look_Ahead_Hough.vhd
vcom  Hough_Kernel_block.vhd
vcom  Gradient_Kernel_System.vhd
vcom  Hybrid_LHT_Kernel.vhd
vcom  Hybrid_LHT.vhd
