-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj_480p\hdlsrc\parallel_lht\Hough_Kernel.vhd
-- Created: 2020-02-27 22:13:58
-- 
-- Generated by MATLAB 9.7 and HDL Coder 3.15
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Hough_Kernel
-- Source Path: parallel_lht/Parallel LHT/Parallel LHT Kernel/Hough Kernel
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Parallel_LHT_pkg.ALL;

ENTITY Hough_Kernel IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        X                                 :   IN    std_logic_vector(9 DOWNTO 0);  -- sfix10
        Y                                 :   IN    std_logic_vector(8 DOWNTO 0);  -- sfix9
        Rho                               :   OUT   vector_of_std_logic_vector10(0 TO 179)  -- sfix10 [180]
        );
END Hough_Kernel;


ARCHITECTURE rtl OF Hough_Kernel IS

  -- Component Declarations
  COMPONENT Hough_Kernel_Symmetric_Look_Ahead
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          X                               :   IN    std_logic_vector(9 DOWNTO 0);  -- sfix10
          Y                               :   IN    std_logic_vector(8 DOWNTO 0);  -- sfix9
          Rho                             :   OUT   vector_of_std_logic_vector10(0 TO 179)  -- sfix10 [180]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Hough_Kernel_Symmetric_Look_Ahead
    USE ENTITY work.Hough_Kernel_Symmetric_Look_Ahead(rtl);

  -- Signals
  SIGNAL Hough_Kernel_Symmetric_Look_Ahead_out1 : vector_of_std_logic_vector10(0 TO 179);  -- ufix10 [180]

BEGIN
  u_Hough_Kernel_Symmetric_Look_Ahead : Hough_Kernel_Symmetric_Look_Ahead
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              X => X,  -- sfix10
              Y => Y,  -- sfix9
              Rho => Hough_Kernel_Symmetric_Look_Ahead_out1  -- sfix10 [180]
              );

  Rho <= Hough_Kernel_Symmetric_Look_Ahead_out1;

END rtl;

