vlib work
vcom  Parallel_LHT_pkg.vhd
vcom  SimpleDualPortRAM_generic.vhd
vcom  Simple_Dual_Port_RAM.vhd
vcom  Block_RAM.vhd
vcom  Accumulator.vhd
vcom  Accumulator_with_Switches.vhd
vcom  Accumulator_Controller.vhd
vcom  Parallel_LHT_Accumulator.vhd
vcom  Hough_Kernel_Symmetric.vhd
vcom  MATLAB_Function.vhd
vcom  Register_Bank.vhd
vcom  Look_Ahead_Hough.vhd
vcom  Hough_Kernel_Symmetric_Look_Ahead.vhd
vcom  Hough_Kernel.vhd
vcom  Parallel_LHT_Kernel.vhd
vcom  Parallel_LHT.vhd
