-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj_240p\hdlsrc\hybrid_lht\Extract_Active_Votes.vhd
-- Created: 2020-03-05 11:51:28
-- 
-- Generated by MATLAB 9.7 and HDL Coder 3.15
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Extract_Active_Votes
-- Source Path: hybrid_lht/Hybrid LHT/Hybrid LHT Kernel/Extract Active Votes
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Hybrid_LHT_pkg.ALL;

ENTITY Extract_Active_Votes IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Theta                             :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
        Index                             :   OUT   vector_of_std_logic_vector8(0 TO 44)  -- uint8 [45]
        );
END Extract_Active_Votes;


ARCHITECTURE rtl OF Extract_Active_Votes IS

  -- Component Declarations
  COMPONENT GetShift
    PORT( Theta                           :   IN    std_logic_vector(7 DOWNTO 0);  -- uint8
          Shift                           :   OUT   std_logic_vector(2 DOWNTO 0)  -- ufix3
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : GetShift
    USE ENTITY work.GetShift(rtl);

  -- Signals
  SIGNAL Theta_unsigned                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL delayMatch_reg                   : vector_of_unsigned8(0 TO 1);  -- ufix8 [2]
  SIGNAL Theta_1                          : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL kconst                           : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL kconst_1                         : unsigned(7 DOWNTO 0);  -- ufix8
  SIGNAL GetShift_out1                    : std_logic_vector(2 DOWNTO 0);  -- ufix3
  SIGNAL GetShift_out1_unsigned           : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL GetShift_out1_1                  : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL Gain1_out1                       : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Gain1_out1_1                     : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Add2_sub_cast                    : signed(8 DOWNTO 0);  -- sfix9
  SIGNAL Add2_sub_cast_1                  : signed(8 DOWNTO 0);  -- sfix9
  SIGNAL Add2_out1                        : signed(8 DOWNTO 0);  -- sfix9
  SIGNAL Constant_out1                    : vector_of_signed6(0 TO 44);  -- sfix6 [45]
  SIGNAL Add_u                            : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Add_out1                         : vector_of_signed10(0 TO 44);  -- sfix10 [45]
  SIGNAL Add_out1_0                       : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Low_out1                         : std_logic;  -- ufix1
  SIGNAL Relational_1_cast                : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop1                : std_logic;
  SIGNAL Add_out1_1                       : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_2_cast                : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop2                : std_logic;
  SIGNAL Add_out1_2                       : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_3_cast                : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop3                : std_logic;
  SIGNAL Add_out1_3                       : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_4_cast                : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop4                : std_logic;
  SIGNAL Add_out1_4                       : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_5_cast                : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop5                : std_logic;
  SIGNAL Add_out1_5                       : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_6_cast                : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop6                : std_logic;
  SIGNAL Add_out1_6                       : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_7_cast                : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop7                : std_logic;
  SIGNAL Add_out1_7                       : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_8_cast                : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop8                : std_logic;
  SIGNAL Add_out1_8                       : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_9_cast                : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop9                : std_logic;
  SIGNAL Add_out1_9                       : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_10_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop10               : std_logic;
  SIGNAL Add_out1_10                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_11_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop11               : std_logic;
  SIGNAL Add_out1_11                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_12_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop12               : std_logic;
  SIGNAL Add_out1_12                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_13_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop13               : std_logic;
  SIGNAL Add_out1_13                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_14_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop14               : std_logic;
  SIGNAL Add_out1_14                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_15_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop15               : std_logic;
  SIGNAL Add_out1_15                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_16_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop16               : std_logic;
  SIGNAL Add_out1_16                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_17_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop17               : std_logic;
  SIGNAL Add_out1_17                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_18_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop18               : std_logic;
  SIGNAL Add_out1_18                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_19_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop19               : std_logic;
  SIGNAL Add_out1_19                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_20_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop20               : std_logic;
  SIGNAL Add_out1_20                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_21_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop21               : std_logic;
  SIGNAL Add_out1_21                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_22_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop22               : std_logic;
  SIGNAL Add_out1_22                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_23_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop23               : std_logic;
  SIGNAL Add_out1_23                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_24_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop24               : std_logic;
  SIGNAL Add_out1_24                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_25_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop25               : std_logic;
  SIGNAL Add_out1_25                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_26_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop26               : std_logic;
  SIGNAL Add_out1_26                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_27_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop27               : std_logic;
  SIGNAL Add_out1_27                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_28_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop28               : std_logic;
  SIGNAL Add_out1_28                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_29_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop29               : std_logic;
  SIGNAL Add_out1_29                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_30_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop30               : std_logic;
  SIGNAL Add_out1_30                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_31_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop31               : std_logic;
  SIGNAL Add_out1_31                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_32_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop32               : std_logic;
  SIGNAL Add_out1_32                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_33_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop33               : std_logic;
  SIGNAL Add_out1_33                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_34_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop34               : std_logic;
  SIGNAL Add_out1_34                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_35_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop35               : std_logic;
  SIGNAL Add_out1_35                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_36_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop36               : std_logic;
  SIGNAL Add_out1_36                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_37_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop37               : std_logic;
  SIGNAL Add_out1_37                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_38_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop38               : std_logic;
  SIGNAL Add_out1_38                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_39_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop39               : std_logic;
  SIGNAL Add_out1_39                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_40_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop40               : std_logic;
  SIGNAL Add_out1_40                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_41_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop41               : std_logic;
  SIGNAL Add_out1_41                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_42_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop42               : std_logic;
  SIGNAL Add_out1_42                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_43_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop43               : std_logic;
  SIGNAL Add_out1_43                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_44_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop44               : std_logic;
  SIGNAL Add_out1_44                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_45_cast               : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Relational_relop45               : std_logic;
  SIGNAL Relational_out1                  : std_logic_vector(0 TO 44);  -- boolean [45]
  SIGNAL Relational_out1_0                : std_logic;
  SIGNAL Add_out1_dtc                     : vector_of_signed11(0 TO 44);  -- sfix11 [45]
  SIGNAL Add_out1_dtc_0                   : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL nTheta_out1                      : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Add3_v                           : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1                        : vector_of_signed11(0 TO 44);  -- sfix11 [45]
  SIGNAL Add3_out1_0                      : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_0         : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL High_out1                        : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Relational1_1_cast               : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop1               : std_logic;
  SIGNAL Relational_out1_1                : std_logic;
  SIGNAL Add_out1_dtc_1                   : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_1                      : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_1         : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_2_cast               : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop2               : std_logic;
  SIGNAL Relational_out1_2                : std_logic;
  SIGNAL Add_out1_dtc_2                   : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_2                      : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_2         : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_3_cast               : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop3               : std_logic;
  SIGNAL Relational_out1_3                : std_logic;
  SIGNAL Add_out1_dtc_3                   : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_3                      : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_3         : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_4_cast               : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop4               : std_logic;
  SIGNAL Relational_out1_4                : std_logic;
  SIGNAL Add_out1_dtc_4                   : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_4                      : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_4         : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_5_cast               : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop5               : std_logic;
  SIGNAL Relational_out1_5                : std_logic;
  SIGNAL Add_out1_dtc_5                   : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_5                      : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_5         : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_6_cast               : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop6               : std_logic;
  SIGNAL Relational_out1_6                : std_logic;
  SIGNAL Add_out1_dtc_6                   : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_6                      : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_6         : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_7_cast               : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop7               : std_logic;
  SIGNAL Relational_out1_7                : std_logic;
  SIGNAL Add_out1_dtc_7                   : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_7                      : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_7         : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_8_cast               : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop8               : std_logic;
  SIGNAL Relational_out1_8                : std_logic;
  SIGNAL Add_out1_dtc_8                   : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_8                      : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_8         : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_9_cast               : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop9               : std_logic;
  SIGNAL Relational_out1_9                : std_logic;
  SIGNAL Add_out1_dtc_9                   : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_9                      : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_9         : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_10_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop10              : std_logic;
  SIGNAL Relational_out1_10               : std_logic;
  SIGNAL Add_out1_dtc_10                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_10                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_10        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_11_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop11              : std_logic;
  SIGNAL Relational_out1_11               : std_logic;
  SIGNAL Add_out1_dtc_11                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_11                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_11        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_12_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop12              : std_logic;
  SIGNAL Relational_out1_12               : std_logic;
  SIGNAL Add_out1_dtc_12                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_12                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_12        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_13_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop13              : std_logic;
  SIGNAL Relational_out1_13               : std_logic;
  SIGNAL Add_out1_dtc_13                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_13                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_13        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_14_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop14              : std_logic;
  SIGNAL Relational_out1_14               : std_logic;
  SIGNAL Add_out1_dtc_14                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_14                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_14        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_15_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop15              : std_logic;
  SIGNAL Relational_out1_15               : std_logic;
  SIGNAL Add_out1_dtc_15                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_15                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_15        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_16_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop16              : std_logic;
  SIGNAL Relational_out1_16               : std_logic;
  SIGNAL Add_out1_dtc_16                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_16                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_16        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_17_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop17              : std_logic;
  SIGNAL Relational_out1_17               : std_logic;
  SIGNAL Add_out1_dtc_17                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_17                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_17        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_18_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop18              : std_logic;
  SIGNAL Relational_out1_18               : std_logic;
  SIGNAL Add_out1_dtc_18                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_18                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_18        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_19_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop19              : std_logic;
  SIGNAL Relational_out1_19               : std_logic;
  SIGNAL Add_out1_dtc_19                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_19                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_19        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_20_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop20              : std_logic;
  SIGNAL Relational_out1_20               : std_logic;
  SIGNAL Add_out1_dtc_20                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_20                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_20        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_21_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop21              : std_logic;
  SIGNAL Relational_out1_21               : std_logic;
  SIGNAL Add_out1_dtc_21                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_21                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_21        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_22_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop22              : std_logic;
  SIGNAL Relational_out1_22               : std_logic;
  SIGNAL Add_out1_dtc_22                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_22                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_22        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_23_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop23              : std_logic;
  SIGNAL Relational_out1_23               : std_logic;
  SIGNAL Add_out1_dtc_23                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_23                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_23        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_24_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop24              : std_logic;
  SIGNAL Relational_out1_24               : std_logic;
  SIGNAL Add_out1_dtc_24                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_24                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_24        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_25_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop25              : std_logic;
  SIGNAL Relational_out1_25               : std_logic;
  SIGNAL Add_out1_dtc_25                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_25                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_25        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_26_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop26              : std_logic;
  SIGNAL Relational_out1_26               : std_logic;
  SIGNAL Add_out1_dtc_26                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_26                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_26        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_27_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop27              : std_logic;
  SIGNAL Relational_out1_27               : std_logic;
  SIGNAL Add_out1_dtc_27                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_27                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_27        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_28_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop28              : std_logic;
  SIGNAL Relational_out1_28               : std_logic;
  SIGNAL Add_out1_dtc_28                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_28                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_28        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_29_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop29              : std_logic;
  SIGNAL Relational_out1_29               : std_logic;
  SIGNAL Add_out1_dtc_29                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_29                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_29        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_30_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop30              : std_logic;
  SIGNAL Relational_out1_30               : std_logic;
  SIGNAL Add_out1_dtc_30                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_30                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_30        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_31_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop31              : std_logic;
  SIGNAL Relational_out1_31               : std_logic;
  SIGNAL Add_out1_dtc_31                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_31                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_31        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_32_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop32              : std_logic;
  SIGNAL Relational_out1_32               : std_logic;
  SIGNAL Add_out1_dtc_32                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_32                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_32        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_33_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop33              : std_logic;
  SIGNAL Relational_out1_33               : std_logic;
  SIGNAL Add_out1_dtc_33                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_33                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_33        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_34_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop34              : std_logic;
  SIGNAL Relational_out1_34               : std_logic;
  SIGNAL Add_out1_dtc_34                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_34                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_34        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_35_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop35              : std_logic;
  SIGNAL Relational_out1_35               : std_logic;
  SIGNAL Add_out1_dtc_35                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_35                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_35        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_36_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop36              : std_logic;
  SIGNAL Relational_out1_36               : std_logic;
  SIGNAL Add_out1_dtc_36                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_36                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_36        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_37_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop37              : std_logic;
  SIGNAL Relational_out1_37               : std_logic;
  SIGNAL Add_out1_dtc_37                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_37                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_37        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_38_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop38              : std_logic;
  SIGNAL Relational_out1_38               : std_logic;
  SIGNAL Add_out1_dtc_38                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_38                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_38        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_39_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop39              : std_logic;
  SIGNAL Relational_out1_39               : std_logic;
  SIGNAL Add_out1_dtc_39                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_39                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_39        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_40_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop40              : std_logic;
  SIGNAL Relational_out1_40               : std_logic;
  SIGNAL Add_out1_dtc_40                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_40                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_40        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_41_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop41              : std_logic;
  SIGNAL Relational_out1_41               : std_logic;
  SIGNAL Add_out1_dtc_41                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_41                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_41        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_42_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop42              : std_logic;
  SIGNAL Relational_out1_42               : std_logic;
  SIGNAL Add_out1_dtc_42                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_42                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_42        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_43_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop43              : std_logic;
  SIGNAL Relational_out1_43               : std_logic;
  SIGNAL Add_out1_dtc_43                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_43                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_43        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_44_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop44              : std_logic;
  SIGNAL Relational_out1_44               : std_logic;
  SIGNAL Add_out1_dtc_44                  : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Add3_out1_44                     : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Multiport_Switch2_out1_44        : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_45_cast              : signed(10 DOWNTO 0);  -- sfix11
  SIGNAL Relational1_relop45              : std_logic;
  SIGNAL Relational1_out1                 : std_logic_vector(0 TO 44);  -- boolean [45]
  SIGNAL Relational1_out1_0               : std_logic;
  SIGNAL Multiport_Switch2_out1           : vector_of_signed11(0 TO 44);  -- sfix11 [45]
  SIGNAL Multiport_Switch2_out1_dtc       : vector_of_signed12(0 TO 44);  -- sfix12 [45]
  SIGNAL Multiport_Switch2_out1_dtc_0     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_v                           : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1                        : vector_of_signed12(0 TO 44);  -- sfix12 [45]
  SIGNAL Relational1_out1_1               : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_1     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_2               : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_2     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_3               : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_3     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_4               : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_4     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_5               : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_5     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_6               : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_6     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_7               : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_7     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_8               : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_8     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_9               : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_9     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_10              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_10    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_11              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_11    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_12              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_12    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_13              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_13    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_14              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_14    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_15              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_15    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_16              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_16    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_17              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_17    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_18              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_18    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_19              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_19    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_20              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_20    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_21              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_21    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_22              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_22    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_23              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_23    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_24              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_24    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_25              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_25    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_26              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_26    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_27              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_27    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_28              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_28    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_29              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_29    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_30              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_30    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_31              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_31    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_32              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_32    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_33              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_33    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_34              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_34    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_35              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_35    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_36              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_36    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_37              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_37    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_38              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_38    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_39              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_39    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_40              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_40    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_41              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_41    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_42              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_42    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_43              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_43    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Relational1_out1_44              : std_logic;
  SIGNAL Multiport_Switch2_out1_dtc_44    : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL High1_out1                       : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Add1_out1_0                      : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_0         : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_1                      : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_1         : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_2                      : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_2         : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_3                      : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_3         : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_4                      : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_4         : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_5                      : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_5         : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_6                      : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_6         : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_7                      : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_7         : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_8                      : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_8         : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_9                      : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_9         : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_10                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_10        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_11                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_11        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_12                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_12        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_13                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_13        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_14                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_14        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_15                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_15        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_16                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_16        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_17                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_17        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_18                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_18        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_19                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_19        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_20                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_20        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_21                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_21        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_22                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_22        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_23                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_23        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_24                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_24        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_25                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_25        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_26                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_26        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_27                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_27        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_28                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_28        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_29                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_29        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_30                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_30        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_31                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_31        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_32                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_32        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_33                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_33        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_34                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_34        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_35                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_35        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_36                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_36        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_37                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_37        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_38                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_38        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_39                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_39        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_40                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_40        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_41                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_41        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_42                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_42        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_43                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_43        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Add1_out1_44                     : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1_44        : signed(11 DOWNTO 0);  -- sfix12
  SIGNAL Multiport_Switch3_out1           : vector_of_signed12(0 TO 44);  -- sfix12 [45]
  SIGNAL Data_Type_Conversion_out1        : vector_of_unsigned8(0 TO 44);  -- uint8 [45]
  SIGNAL Add4_out1                        : vector_of_unsigned8(0 TO 44);  -- uint8 [45]
  SIGNAL Selector4_out1                   : vector_of_unsigned8(0 TO 44);  -- uint8 [45]

BEGIN
  -- Check the indices to ensure they are in the correct limits

  u_GetShift : GetShift
    PORT MAP( Theta => Theta,  -- uint8
              Shift => GetShift_out1  -- ufix3
              );

  Theta_unsigned <= unsigned(Theta);

  delayMatch_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg <= (OTHERS => to_unsigned(16#00#, 8));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delayMatch_reg(0) <= Theta_unsigned;
        delayMatch_reg(1) <= delayMatch_reg(0);
      END IF;
    END IF;
  END PROCESS delayMatch_process;

  Theta_1 <= delayMatch_reg(1);

  kconst <= to_unsigned(16#2D#, 8);

  HwModeRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      kconst_1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        kconst_1 <= kconst;
      END IF;
    END IF;
  END PROCESS HwModeRegister_process;


  GetShift_out1_unsigned <= unsigned(GetShift_out1);

  HwModeRegister1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      GetShift_out1_1 <= to_unsigned(16#0#, 3);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        GetShift_out1_1 <= GetShift_out1_unsigned;
      END IF;
    END IF;
  END PROCESS HwModeRegister1_process;


  Gain1_out1 <= resize(kconst_1 * GetShift_out1_1, 8);

  PipelineRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Gain1_out1_1 <= to_unsigned(16#00#, 8);
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        Gain1_out1_1 <= Gain1_out1;
      END IF;
    END IF;
  END PROCESS PipelineRegister_process;


  Add2_sub_cast <= signed(resize(Theta_1, 9));
  Add2_sub_cast_1 <= signed(resize(Gain1_out1_1, 9));
  Add2_out1 <= Add2_sub_cast - Add2_sub_cast_1;

  Constant_out1(0) <= to_signed(-16#16#, 6);
  Constant_out1(1) <= to_signed(-16#15#, 6);
  Constant_out1(2) <= to_signed(-16#14#, 6);
  Constant_out1(3) <= to_signed(-16#13#, 6);
  Constant_out1(4) <= to_signed(-16#12#, 6);
  Constant_out1(5) <= to_signed(-16#11#, 6);
  Constant_out1(6) <= to_signed(-16#10#, 6);
  Constant_out1(7) <= to_signed(-16#0F#, 6);
  Constant_out1(8) <= to_signed(-16#0E#, 6);
  Constant_out1(9) <= to_signed(-16#0D#, 6);
  Constant_out1(10) <= to_signed(-16#0C#, 6);
  Constant_out1(11) <= to_signed(-16#0B#, 6);
  Constant_out1(12) <= to_signed(-16#0A#, 6);
  Constant_out1(13) <= to_signed(-16#09#, 6);
  Constant_out1(14) <= to_signed(-16#08#, 6);
  Constant_out1(15) <= to_signed(-16#07#, 6);
  Constant_out1(16) <= to_signed(-16#06#, 6);
  Constant_out1(17) <= to_signed(-16#05#, 6);
  Constant_out1(18) <= to_signed(-16#04#, 6);
  Constant_out1(19) <= to_signed(-16#03#, 6);
  Constant_out1(20) <= to_signed(-16#02#, 6);
  Constant_out1(21) <= to_signed(-16#01#, 6);
  Constant_out1(22) <= to_signed(16#00#, 6);
  Constant_out1(23) <= to_signed(16#01#, 6);
  Constant_out1(24) <= to_signed(16#02#, 6);
  Constant_out1(25) <= to_signed(16#03#, 6);
  Constant_out1(26) <= to_signed(16#04#, 6);
  Constant_out1(27) <= to_signed(16#05#, 6);
  Constant_out1(28) <= to_signed(16#06#, 6);
  Constant_out1(29) <= to_signed(16#07#, 6);
  Constant_out1(30) <= to_signed(16#08#, 6);
  Constant_out1(31) <= to_signed(16#09#, 6);
  Constant_out1(32) <= to_signed(16#0A#, 6);
  Constant_out1(33) <= to_signed(16#0B#, 6);
  Constant_out1(34) <= to_signed(16#0C#, 6);
  Constant_out1(35) <= to_signed(16#0D#, 6);
  Constant_out1(36) <= to_signed(16#0E#, 6);
  Constant_out1(37) <= to_signed(16#0F#, 6);
  Constant_out1(38) <= to_signed(16#10#, 6);
  Constant_out1(39) <= to_signed(16#11#, 6);
  Constant_out1(40) <= to_signed(16#12#, 6);
  Constant_out1(41) <= to_signed(16#13#, 6);
  Constant_out1(42) <= to_signed(16#14#, 6);
  Constant_out1(43) <= to_signed(16#15#, 6);
  Constant_out1(44) <= to_signed(16#16#, 6);

  Add_u <= resize(Add2_out1, 10);

  Add_out1_gen: FOR t_0 IN 0 TO 44 GENERATE
    Add_out1(t_0) <= Add_u + resize(Constant_out1(t_0), 10);
  END GENERATE Add_out1_gen;


  Add_out1_0 <= Add_out1(0);

  Low_out1 <= '0';

  Relational_1_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop1 <= '1' WHEN Add_out1_0 < Relational_1_cast ELSE
      '0';

  Add_out1_1 <= Add_out1(1);

  Relational_2_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop2 <= '1' WHEN Add_out1_1 < Relational_2_cast ELSE
      '0';

  Add_out1_2 <= Add_out1(2);

  Relational_3_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop3 <= '1' WHEN Add_out1_2 < Relational_3_cast ELSE
      '0';

  Add_out1_3 <= Add_out1(3);

  Relational_4_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop4 <= '1' WHEN Add_out1_3 < Relational_4_cast ELSE
      '0';

  Add_out1_4 <= Add_out1(4);

  Relational_5_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop5 <= '1' WHEN Add_out1_4 < Relational_5_cast ELSE
      '0';

  Add_out1_5 <= Add_out1(5);

  Relational_6_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop6 <= '1' WHEN Add_out1_5 < Relational_6_cast ELSE
      '0';

  Add_out1_6 <= Add_out1(6);

  Relational_7_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop7 <= '1' WHEN Add_out1_6 < Relational_7_cast ELSE
      '0';

  Add_out1_7 <= Add_out1(7);

  Relational_8_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop8 <= '1' WHEN Add_out1_7 < Relational_8_cast ELSE
      '0';

  Add_out1_8 <= Add_out1(8);

  Relational_9_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop9 <= '1' WHEN Add_out1_8 < Relational_9_cast ELSE
      '0';

  Add_out1_9 <= Add_out1(9);

  Relational_10_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop10 <= '1' WHEN Add_out1_9 < Relational_10_cast ELSE
      '0';

  Add_out1_10 <= Add_out1(10);

  Relational_11_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop11 <= '1' WHEN Add_out1_10 < Relational_11_cast ELSE
      '0';

  Add_out1_11 <= Add_out1(11);

  Relational_12_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop12 <= '1' WHEN Add_out1_11 < Relational_12_cast ELSE
      '0';

  Add_out1_12 <= Add_out1(12);

  Relational_13_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop13 <= '1' WHEN Add_out1_12 < Relational_13_cast ELSE
      '0';

  Add_out1_13 <= Add_out1(13);

  Relational_14_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop14 <= '1' WHEN Add_out1_13 < Relational_14_cast ELSE
      '0';

  Add_out1_14 <= Add_out1(14);

  Relational_15_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop15 <= '1' WHEN Add_out1_14 < Relational_15_cast ELSE
      '0';

  Add_out1_15 <= Add_out1(15);

  Relational_16_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop16 <= '1' WHEN Add_out1_15 < Relational_16_cast ELSE
      '0';

  Add_out1_16 <= Add_out1(16);

  Relational_17_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop17 <= '1' WHEN Add_out1_16 < Relational_17_cast ELSE
      '0';

  Add_out1_17 <= Add_out1(17);

  Relational_18_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop18 <= '1' WHEN Add_out1_17 < Relational_18_cast ELSE
      '0';

  Add_out1_18 <= Add_out1(18);

  Relational_19_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop19 <= '1' WHEN Add_out1_18 < Relational_19_cast ELSE
      '0';

  Add_out1_19 <= Add_out1(19);

  Relational_20_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop20 <= '1' WHEN Add_out1_19 < Relational_20_cast ELSE
      '0';

  Add_out1_20 <= Add_out1(20);

  Relational_21_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop21 <= '1' WHEN Add_out1_20 < Relational_21_cast ELSE
      '0';

  Add_out1_21 <= Add_out1(21);

  Relational_22_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop22 <= '1' WHEN Add_out1_21 < Relational_22_cast ELSE
      '0';

  Add_out1_22 <= Add_out1(22);

  Relational_23_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop23 <= '1' WHEN Add_out1_22 < Relational_23_cast ELSE
      '0';

  Add_out1_23 <= Add_out1(23);

  Relational_24_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop24 <= '1' WHEN Add_out1_23 < Relational_24_cast ELSE
      '0';

  Add_out1_24 <= Add_out1(24);

  Relational_25_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop25 <= '1' WHEN Add_out1_24 < Relational_25_cast ELSE
      '0';

  Add_out1_25 <= Add_out1(25);

  Relational_26_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop26 <= '1' WHEN Add_out1_25 < Relational_26_cast ELSE
      '0';

  Add_out1_26 <= Add_out1(26);

  Relational_27_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop27 <= '1' WHEN Add_out1_26 < Relational_27_cast ELSE
      '0';

  Add_out1_27 <= Add_out1(27);

  Relational_28_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop28 <= '1' WHEN Add_out1_27 < Relational_28_cast ELSE
      '0';

  Add_out1_28 <= Add_out1(28);

  Relational_29_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop29 <= '1' WHEN Add_out1_28 < Relational_29_cast ELSE
      '0';

  Add_out1_29 <= Add_out1(29);

  Relational_30_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop30 <= '1' WHEN Add_out1_29 < Relational_30_cast ELSE
      '0';

  Add_out1_30 <= Add_out1(30);

  Relational_31_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop31 <= '1' WHEN Add_out1_30 < Relational_31_cast ELSE
      '0';

  Add_out1_31 <= Add_out1(31);

  Relational_32_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop32 <= '1' WHEN Add_out1_31 < Relational_32_cast ELSE
      '0';

  Add_out1_32 <= Add_out1(32);

  Relational_33_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop33 <= '1' WHEN Add_out1_32 < Relational_33_cast ELSE
      '0';

  Add_out1_33 <= Add_out1(33);

  Relational_34_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop34 <= '1' WHEN Add_out1_33 < Relational_34_cast ELSE
      '0';

  Add_out1_34 <= Add_out1(34);

  Relational_35_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop35 <= '1' WHEN Add_out1_34 < Relational_35_cast ELSE
      '0';

  Add_out1_35 <= Add_out1(35);

  Relational_36_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop36 <= '1' WHEN Add_out1_35 < Relational_36_cast ELSE
      '0';

  Add_out1_36 <= Add_out1(36);

  Relational_37_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop37 <= '1' WHEN Add_out1_36 < Relational_37_cast ELSE
      '0';

  Add_out1_37 <= Add_out1(37);

  Relational_38_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop38 <= '1' WHEN Add_out1_37 < Relational_38_cast ELSE
      '0';

  Add_out1_38 <= Add_out1(38);

  Relational_39_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop39 <= '1' WHEN Add_out1_38 < Relational_39_cast ELSE
      '0';

  Add_out1_39 <= Add_out1(39);

  Relational_40_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop40 <= '1' WHEN Add_out1_39 < Relational_40_cast ELSE
      '0';

  Add_out1_40 <= Add_out1(40);

  Relational_41_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop41 <= '1' WHEN Add_out1_40 < Relational_41_cast ELSE
      '0';

  Add_out1_41 <= Add_out1(41);

  Relational_42_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop42 <= '1' WHEN Add_out1_41 < Relational_42_cast ELSE
      '0';

  Add_out1_42 <= Add_out1(42);

  Relational_43_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop43 <= '1' WHEN Add_out1_42 < Relational_43_cast ELSE
      '0';

  Add_out1_43 <= Add_out1(43);

  Relational_44_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop44 <= '1' WHEN Add_out1_43 < Relational_44_cast ELSE
      '0';

  Add_out1_44 <= Add_out1(44);

  Relational_45_cast <= '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & '0' & Low_out1;
  
  Relational_relop45 <= '1' WHEN Add_out1_44 < Relational_45_cast ELSE
      '0';

  Relational_out1(0) <= Relational_relop1;
  Relational_out1(1) <= Relational_relop2;
  Relational_out1(2) <= Relational_relop3;
  Relational_out1(3) <= Relational_relop4;
  Relational_out1(4) <= Relational_relop5;
  Relational_out1(5) <= Relational_relop6;
  Relational_out1(6) <= Relational_relop7;
  Relational_out1(7) <= Relational_relop8;
  Relational_out1(8) <= Relational_relop9;
  Relational_out1(9) <= Relational_relop10;
  Relational_out1(10) <= Relational_relop11;
  Relational_out1(11) <= Relational_relop12;
  Relational_out1(12) <= Relational_relop13;
  Relational_out1(13) <= Relational_relop14;
  Relational_out1(14) <= Relational_relop15;
  Relational_out1(15) <= Relational_relop16;
  Relational_out1(16) <= Relational_relop17;
  Relational_out1(17) <= Relational_relop18;
  Relational_out1(18) <= Relational_relop19;
  Relational_out1(19) <= Relational_relop20;
  Relational_out1(20) <= Relational_relop21;
  Relational_out1(21) <= Relational_relop22;
  Relational_out1(22) <= Relational_relop23;
  Relational_out1(23) <= Relational_relop24;
  Relational_out1(24) <= Relational_relop25;
  Relational_out1(25) <= Relational_relop26;
  Relational_out1(26) <= Relational_relop27;
  Relational_out1(27) <= Relational_relop28;
  Relational_out1(28) <= Relational_relop29;
  Relational_out1(29) <= Relational_relop30;
  Relational_out1(30) <= Relational_relop31;
  Relational_out1(31) <= Relational_relop32;
  Relational_out1(32) <= Relational_relop33;
  Relational_out1(33) <= Relational_relop34;
  Relational_out1(34) <= Relational_relop35;
  Relational_out1(35) <= Relational_relop36;
  Relational_out1(36) <= Relational_relop37;
  Relational_out1(37) <= Relational_relop38;
  Relational_out1(38) <= Relational_relop39;
  Relational_out1(39) <= Relational_relop40;
  Relational_out1(40) <= Relational_relop41;
  Relational_out1(41) <= Relational_relop42;
  Relational_out1(42) <= Relational_relop43;
  Relational_out1(43) <= Relational_relop44;
  Relational_out1(44) <= Relational_relop45;

  Relational_out1_0 <= Relational_out1(0);


  Add_out1_dtc_gen: FOR ii IN 0 TO 44 GENERATE
    Add_out1_dtc(ii) <= resize(Add_out1(ii), 11);
  END GENERATE Add_out1_dtc_gen;


  Add_out1_dtc_0 <= Add_out1_dtc(0);

  nTheta_out1 <= to_unsigned(16#2D#, 8);

  Add3_v <= signed(resize(nTheta_out1, 11));

  Add3_out1_gen: FOR t_01 IN 0 TO 44 GENERATE
    Add3_out1(t_01) <= resize(Add_out1(t_01), 11) + Add3_v;
  END GENERATE Add3_out1_gen;


  Add3_out1_0 <= Add3_out1(0);

  
  Multiport_Switch2_out1_0 <= Add_out1_dtc_0 WHEN Relational_out1_0 = '0' ELSE
      Add3_out1_0;

  High_out1 <= to_unsigned(16#2C#, 8);

  Relational1_1_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop1 <= '1' WHEN Multiport_Switch2_out1_0 > Relational1_1_cast ELSE
      '0';

  Relational_out1_1 <= Relational_out1(1);

  Add_out1_dtc_1 <= Add_out1_dtc(1);

  Add3_out1_1 <= Add3_out1(1);

  
  Multiport_Switch2_out1_1 <= Add_out1_dtc_1 WHEN Relational_out1_1 = '0' ELSE
      Add3_out1_1;

  Relational1_2_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop2 <= '1' WHEN Multiport_Switch2_out1_1 > Relational1_2_cast ELSE
      '0';

  Relational_out1_2 <= Relational_out1(2);

  Add_out1_dtc_2 <= Add_out1_dtc(2);

  Add3_out1_2 <= Add3_out1(2);

  
  Multiport_Switch2_out1_2 <= Add_out1_dtc_2 WHEN Relational_out1_2 = '0' ELSE
      Add3_out1_2;

  Relational1_3_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop3 <= '1' WHEN Multiport_Switch2_out1_2 > Relational1_3_cast ELSE
      '0';

  Relational_out1_3 <= Relational_out1(3);

  Add_out1_dtc_3 <= Add_out1_dtc(3);

  Add3_out1_3 <= Add3_out1(3);

  
  Multiport_Switch2_out1_3 <= Add_out1_dtc_3 WHEN Relational_out1_3 = '0' ELSE
      Add3_out1_3;

  Relational1_4_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop4 <= '1' WHEN Multiport_Switch2_out1_3 > Relational1_4_cast ELSE
      '0';

  Relational_out1_4 <= Relational_out1(4);

  Add_out1_dtc_4 <= Add_out1_dtc(4);

  Add3_out1_4 <= Add3_out1(4);

  
  Multiport_Switch2_out1_4 <= Add_out1_dtc_4 WHEN Relational_out1_4 = '0' ELSE
      Add3_out1_4;

  Relational1_5_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop5 <= '1' WHEN Multiport_Switch2_out1_4 > Relational1_5_cast ELSE
      '0';

  Relational_out1_5 <= Relational_out1(5);

  Add_out1_dtc_5 <= Add_out1_dtc(5);

  Add3_out1_5 <= Add3_out1(5);

  
  Multiport_Switch2_out1_5 <= Add_out1_dtc_5 WHEN Relational_out1_5 = '0' ELSE
      Add3_out1_5;

  Relational1_6_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop6 <= '1' WHEN Multiport_Switch2_out1_5 > Relational1_6_cast ELSE
      '0';

  Relational_out1_6 <= Relational_out1(6);

  Add_out1_dtc_6 <= Add_out1_dtc(6);

  Add3_out1_6 <= Add3_out1(6);

  
  Multiport_Switch2_out1_6 <= Add_out1_dtc_6 WHEN Relational_out1_6 = '0' ELSE
      Add3_out1_6;

  Relational1_7_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop7 <= '1' WHEN Multiport_Switch2_out1_6 > Relational1_7_cast ELSE
      '0';

  Relational_out1_7 <= Relational_out1(7);

  Add_out1_dtc_7 <= Add_out1_dtc(7);

  Add3_out1_7 <= Add3_out1(7);

  
  Multiport_Switch2_out1_7 <= Add_out1_dtc_7 WHEN Relational_out1_7 = '0' ELSE
      Add3_out1_7;

  Relational1_8_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop8 <= '1' WHEN Multiport_Switch2_out1_7 > Relational1_8_cast ELSE
      '0';

  Relational_out1_8 <= Relational_out1(8);

  Add_out1_dtc_8 <= Add_out1_dtc(8);

  Add3_out1_8 <= Add3_out1(8);

  
  Multiport_Switch2_out1_8 <= Add_out1_dtc_8 WHEN Relational_out1_8 = '0' ELSE
      Add3_out1_8;

  Relational1_9_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop9 <= '1' WHEN Multiport_Switch2_out1_8 > Relational1_9_cast ELSE
      '0';

  Relational_out1_9 <= Relational_out1(9);

  Add_out1_dtc_9 <= Add_out1_dtc(9);

  Add3_out1_9 <= Add3_out1(9);

  
  Multiport_Switch2_out1_9 <= Add_out1_dtc_9 WHEN Relational_out1_9 = '0' ELSE
      Add3_out1_9;

  Relational1_10_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop10 <= '1' WHEN Multiport_Switch2_out1_9 > Relational1_10_cast ELSE
      '0';

  Relational_out1_10 <= Relational_out1(10);

  Add_out1_dtc_10 <= Add_out1_dtc(10);

  Add3_out1_10 <= Add3_out1(10);

  
  Multiport_Switch2_out1_10 <= Add_out1_dtc_10 WHEN Relational_out1_10 = '0' ELSE
      Add3_out1_10;

  Relational1_11_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop11 <= '1' WHEN Multiport_Switch2_out1_10 > Relational1_11_cast ELSE
      '0';

  Relational_out1_11 <= Relational_out1(11);

  Add_out1_dtc_11 <= Add_out1_dtc(11);

  Add3_out1_11 <= Add3_out1(11);

  
  Multiport_Switch2_out1_11 <= Add_out1_dtc_11 WHEN Relational_out1_11 = '0' ELSE
      Add3_out1_11;

  Relational1_12_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop12 <= '1' WHEN Multiport_Switch2_out1_11 > Relational1_12_cast ELSE
      '0';

  Relational_out1_12 <= Relational_out1(12);

  Add_out1_dtc_12 <= Add_out1_dtc(12);

  Add3_out1_12 <= Add3_out1(12);

  
  Multiport_Switch2_out1_12 <= Add_out1_dtc_12 WHEN Relational_out1_12 = '0' ELSE
      Add3_out1_12;

  Relational1_13_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop13 <= '1' WHEN Multiport_Switch2_out1_12 > Relational1_13_cast ELSE
      '0';

  Relational_out1_13 <= Relational_out1(13);

  Add_out1_dtc_13 <= Add_out1_dtc(13);

  Add3_out1_13 <= Add3_out1(13);

  
  Multiport_Switch2_out1_13 <= Add_out1_dtc_13 WHEN Relational_out1_13 = '0' ELSE
      Add3_out1_13;

  Relational1_14_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop14 <= '1' WHEN Multiport_Switch2_out1_13 > Relational1_14_cast ELSE
      '0';

  Relational_out1_14 <= Relational_out1(14);

  Add_out1_dtc_14 <= Add_out1_dtc(14);

  Add3_out1_14 <= Add3_out1(14);

  
  Multiport_Switch2_out1_14 <= Add_out1_dtc_14 WHEN Relational_out1_14 = '0' ELSE
      Add3_out1_14;

  Relational1_15_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop15 <= '1' WHEN Multiport_Switch2_out1_14 > Relational1_15_cast ELSE
      '0';

  Relational_out1_15 <= Relational_out1(15);

  Add_out1_dtc_15 <= Add_out1_dtc(15);

  Add3_out1_15 <= Add3_out1(15);

  
  Multiport_Switch2_out1_15 <= Add_out1_dtc_15 WHEN Relational_out1_15 = '0' ELSE
      Add3_out1_15;

  Relational1_16_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop16 <= '1' WHEN Multiport_Switch2_out1_15 > Relational1_16_cast ELSE
      '0';

  Relational_out1_16 <= Relational_out1(16);

  Add_out1_dtc_16 <= Add_out1_dtc(16);

  Add3_out1_16 <= Add3_out1(16);

  
  Multiport_Switch2_out1_16 <= Add_out1_dtc_16 WHEN Relational_out1_16 = '0' ELSE
      Add3_out1_16;

  Relational1_17_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop17 <= '1' WHEN Multiport_Switch2_out1_16 > Relational1_17_cast ELSE
      '0';

  Relational_out1_17 <= Relational_out1(17);

  Add_out1_dtc_17 <= Add_out1_dtc(17);

  Add3_out1_17 <= Add3_out1(17);

  
  Multiport_Switch2_out1_17 <= Add_out1_dtc_17 WHEN Relational_out1_17 = '0' ELSE
      Add3_out1_17;

  Relational1_18_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop18 <= '1' WHEN Multiport_Switch2_out1_17 > Relational1_18_cast ELSE
      '0';

  Relational_out1_18 <= Relational_out1(18);

  Add_out1_dtc_18 <= Add_out1_dtc(18);

  Add3_out1_18 <= Add3_out1(18);

  
  Multiport_Switch2_out1_18 <= Add_out1_dtc_18 WHEN Relational_out1_18 = '0' ELSE
      Add3_out1_18;

  Relational1_19_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop19 <= '1' WHEN Multiport_Switch2_out1_18 > Relational1_19_cast ELSE
      '0';

  Relational_out1_19 <= Relational_out1(19);

  Add_out1_dtc_19 <= Add_out1_dtc(19);

  Add3_out1_19 <= Add3_out1(19);

  
  Multiport_Switch2_out1_19 <= Add_out1_dtc_19 WHEN Relational_out1_19 = '0' ELSE
      Add3_out1_19;

  Relational1_20_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop20 <= '1' WHEN Multiport_Switch2_out1_19 > Relational1_20_cast ELSE
      '0';

  Relational_out1_20 <= Relational_out1(20);

  Add_out1_dtc_20 <= Add_out1_dtc(20);

  Add3_out1_20 <= Add3_out1(20);

  
  Multiport_Switch2_out1_20 <= Add_out1_dtc_20 WHEN Relational_out1_20 = '0' ELSE
      Add3_out1_20;

  Relational1_21_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop21 <= '1' WHEN Multiport_Switch2_out1_20 > Relational1_21_cast ELSE
      '0';

  Relational_out1_21 <= Relational_out1(21);

  Add_out1_dtc_21 <= Add_out1_dtc(21);

  Add3_out1_21 <= Add3_out1(21);

  
  Multiport_Switch2_out1_21 <= Add_out1_dtc_21 WHEN Relational_out1_21 = '0' ELSE
      Add3_out1_21;

  Relational1_22_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop22 <= '1' WHEN Multiport_Switch2_out1_21 > Relational1_22_cast ELSE
      '0';

  Relational_out1_22 <= Relational_out1(22);

  Add_out1_dtc_22 <= Add_out1_dtc(22);

  Add3_out1_22 <= Add3_out1(22);

  
  Multiport_Switch2_out1_22 <= Add_out1_dtc_22 WHEN Relational_out1_22 = '0' ELSE
      Add3_out1_22;

  Relational1_23_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop23 <= '1' WHEN Multiport_Switch2_out1_22 > Relational1_23_cast ELSE
      '0';

  Relational_out1_23 <= Relational_out1(23);

  Add_out1_dtc_23 <= Add_out1_dtc(23);

  Add3_out1_23 <= Add3_out1(23);

  
  Multiport_Switch2_out1_23 <= Add_out1_dtc_23 WHEN Relational_out1_23 = '0' ELSE
      Add3_out1_23;

  Relational1_24_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop24 <= '1' WHEN Multiport_Switch2_out1_23 > Relational1_24_cast ELSE
      '0';

  Relational_out1_24 <= Relational_out1(24);

  Add_out1_dtc_24 <= Add_out1_dtc(24);

  Add3_out1_24 <= Add3_out1(24);

  
  Multiport_Switch2_out1_24 <= Add_out1_dtc_24 WHEN Relational_out1_24 = '0' ELSE
      Add3_out1_24;

  Relational1_25_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop25 <= '1' WHEN Multiport_Switch2_out1_24 > Relational1_25_cast ELSE
      '0';

  Relational_out1_25 <= Relational_out1(25);

  Add_out1_dtc_25 <= Add_out1_dtc(25);

  Add3_out1_25 <= Add3_out1(25);

  
  Multiport_Switch2_out1_25 <= Add_out1_dtc_25 WHEN Relational_out1_25 = '0' ELSE
      Add3_out1_25;

  Relational1_26_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop26 <= '1' WHEN Multiport_Switch2_out1_25 > Relational1_26_cast ELSE
      '0';

  Relational_out1_26 <= Relational_out1(26);

  Add_out1_dtc_26 <= Add_out1_dtc(26);

  Add3_out1_26 <= Add3_out1(26);

  
  Multiport_Switch2_out1_26 <= Add_out1_dtc_26 WHEN Relational_out1_26 = '0' ELSE
      Add3_out1_26;

  Relational1_27_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop27 <= '1' WHEN Multiport_Switch2_out1_26 > Relational1_27_cast ELSE
      '0';

  Relational_out1_27 <= Relational_out1(27);

  Add_out1_dtc_27 <= Add_out1_dtc(27);

  Add3_out1_27 <= Add3_out1(27);

  
  Multiport_Switch2_out1_27 <= Add_out1_dtc_27 WHEN Relational_out1_27 = '0' ELSE
      Add3_out1_27;

  Relational1_28_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop28 <= '1' WHEN Multiport_Switch2_out1_27 > Relational1_28_cast ELSE
      '0';

  Relational_out1_28 <= Relational_out1(28);

  Add_out1_dtc_28 <= Add_out1_dtc(28);

  Add3_out1_28 <= Add3_out1(28);

  
  Multiport_Switch2_out1_28 <= Add_out1_dtc_28 WHEN Relational_out1_28 = '0' ELSE
      Add3_out1_28;

  Relational1_29_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop29 <= '1' WHEN Multiport_Switch2_out1_28 > Relational1_29_cast ELSE
      '0';

  Relational_out1_29 <= Relational_out1(29);

  Add_out1_dtc_29 <= Add_out1_dtc(29);

  Add3_out1_29 <= Add3_out1(29);

  
  Multiport_Switch2_out1_29 <= Add_out1_dtc_29 WHEN Relational_out1_29 = '0' ELSE
      Add3_out1_29;

  Relational1_30_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop30 <= '1' WHEN Multiport_Switch2_out1_29 > Relational1_30_cast ELSE
      '0';

  Relational_out1_30 <= Relational_out1(30);

  Add_out1_dtc_30 <= Add_out1_dtc(30);

  Add3_out1_30 <= Add3_out1(30);

  
  Multiport_Switch2_out1_30 <= Add_out1_dtc_30 WHEN Relational_out1_30 = '0' ELSE
      Add3_out1_30;

  Relational1_31_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop31 <= '1' WHEN Multiport_Switch2_out1_30 > Relational1_31_cast ELSE
      '0';

  Relational_out1_31 <= Relational_out1(31);

  Add_out1_dtc_31 <= Add_out1_dtc(31);

  Add3_out1_31 <= Add3_out1(31);

  
  Multiport_Switch2_out1_31 <= Add_out1_dtc_31 WHEN Relational_out1_31 = '0' ELSE
      Add3_out1_31;

  Relational1_32_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop32 <= '1' WHEN Multiport_Switch2_out1_31 > Relational1_32_cast ELSE
      '0';

  Relational_out1_32 <= Relational_out1(32);

  Add_out1_dtc_32 <= Add_out1_dtc(32);

  Add3_out1_32 <= Add3_out1(32);

  
  Multiport_Switch2_out1_32 <= Add_out1_dtc_32 WHEN Relational_out1_32 = '0' ELSE
      Add3_out1_32;

  Relational1_33_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop33 <= '1' WHEN Multiport_Switch2_out1_32 > Relational1_33_cast ELSE
      '0';

  Relational_out1_33 <= Relational_out1(33);

  Add_out1_dtc_33 <= Add_out1_dtc(33);

  Add3_out1_33 <= Add3_out1(33);

  
  Multiport_Switch2_out1_33 <= Add_out1_dtc_33 WHEN Relational_out1_33 = '0' ELSE
      Add3_out1_33;

  Relational1_34_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop34 <= '1' WHEN Multiport_Switch2_out1_33 > Relational1_34_cast ELSE
      '0';

  Relational_out1_34 <= Relational_out1(34);

  Add_out1_dtc_34 <= Add_out1_dtc(34);

  Add3_out1_34 <= Add3_out1(34);

  
  Multiport_Switch2_out1_34 <= Add_out1_dtc_34 WHEN Relational_out1_34 = '0' ELSE
      Add3_out1_34;

  Relational1_35_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop35 <= '1' WHEN Multiport_Switch2_out1_34 > Relational1_35_cast ELSE
      '0';

  Relational_out1_35 <= Relational_out1(35);

  Add_out1_dtc_35 <= Add_out1_dtc(35);

  Add3_out1_35 <= Add3_out1(35);

  
  Multiport_Switch2_out1_35 <= Add_out1_dtc_35 WHEN Relational_out1_35 = '0' ELSE
      Add3_out1_35;

  Relational1_36_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop36 <= '1' WHEN Multiport_Switch2_out1_35 > Relational1_36_cast ELSE
      '0';

  Relational_out1_36 <= Relational_out1(36);

  Add_out1_dtc_36 <= Add_out1_dtc(36);

  Add3_out1_36 <= Add3_out1(36);

  
  Multiport_Switch2_out1_36 <= Add_out1_dtc_36 WHEN Relational_out1_36 = '0' ELSE
      Add3_out1_36;

  Relational1_37_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop37 <= '1' WHEN Multiport_Switch2_out1_36 > Relational1_37_cast ELSE
      '0';

  Relational_out1_37 <= Relational_out1(37);

  Add_out1_dtc_37 <= Add_out1_dtc(37);

  Add3_out1_37 <= Add3_out1(37);

  
  Multiport_Switch2_out1_37 <= Add_out1_dtc_37 WHEN Relational_out1_37 = '0' ELSE
      Add3_out1_37;

  Relational1_38_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop38 <= '1' WHEN Multiport_Switch2_out1_37 > Relational1_38_cast ELSE
      '0';

  Relational_out1_38 <= Relational_out1(38);

  Add_out1_dtc_38 <= Add_out1_dtc(38);

  Add3_out1_38 <= Add3_out1(38);

  
  Multiport_Switch2_out1_38 <= Add_out1_dtc_38 WHEN Relational_out1_38 = '0' ELSE
      Add3_out1_38;

  Relational1_39_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop39 <= '1' WHEN Multiport_Switch2_out1_38 > Relational1_39_cast ELSE
      '0';

  Relational_out1_39 <= Relational_out1(39);

  Add_out1_dtc_39 <= Add_out1_dtc(39);

  Add3_out1_39 <= Add3_out1(39);

  
  Multiport_Switch2_out1_39 <= Add_out1_dtc_39 WHEN Relational_out1_39 = '0' ELSE
      Add3_out1_39;

  Relational1_40_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop40 <= '1' WHEN Multiport_Switch2_out1_39 > Relational1_40_cast ELSE
      '0';

  Relational_out1_40 <= Relational_out1(40);

  Add_out1_dtc_40 <= Add_out1_dtc(40);

  Add3_out1_40 <= Add3_out1(40);

  
  Multiport_Switch2_out1_40 <= Add_out1_dtc_40 WHEN Relational_out1_40 = '0' ELSE
      Add3_out1_40;

  Relational1_41_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop41 <= '1' WHEN Multiport_Switch2_out1_40 > Relational1_41_cast ELSE
      '0';

  Relational_out1_41 <= Relational_out1(41);

  Add_out1_dtc_41 <= Add_out1_dtc(41);

  Add3_out1_41 <= Add3_out1(41);

  
  Multiport_Switch2_out1_41 <= Add_out1_dtc_41 WHEN Relational_out1_41 = '0' ELSE
      Add3_out1_41;

  Relational1_42_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop42 <= '1' WHEN Multiport_Switch2_out1_41 > Relational1_42_cast ELSE
      '0';

  Relational_out1_42 <= Relational_out1(42);

  Add_out1_dtc_42 <= Add_out1_dtc(42);

  Add3_out1_42 <= Add3_out1(42);

  
  Multiport_Switch2_out1_42 <= Add_out1_dtc_42 WHEN Relational_out1_42 = '0' ELSE
      Add3_out1_42;

  Relational1_43_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop43 <= '1' WHEN Multiport_Switch2_out1_42 > Relational1_43_cast ELSE
      '0';

  Relational_out1_43 <= Relational_out1(43);

  Add_out1_dtc_43 <= Add_out1_dtc(43);

  Add3_out1_43 <= Add3_out1(43);

  
  Multiport_Switch2_out1_43 <= Add_out1_dtc_43 WHEN Relational_out1_43 = '0' ELSE
      Add3_out1_43;

  Relational1_44_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop44 <= '1' WHEN Multiport_Switch2_out1_43 > Relational1_44_cast ELSE
      '0';

  Relational_out1_44 <= Relational_out1(44);

  Add_out1_dtc_44 <= Add_out1_dtc(44);

  Add3_out1_44 <= Add3_out1(44);

  
  Multiport_Switch2_out1_44 <= Add_out1_dtc_44 WHEN Relational_out1_44 = '0' ELSE
      Add3_out1_44;

  Relational1_45_cast <= signed(resize(High_out1, 11));
  
  Relational1_relop45 <= '1' WHEN Multiport_Switch2_out1_44 > Relational1_45_cast ELSE
      '0';

  Relational1_out1(0) <= Relational1_relop1;
  Relational1_out1(1) <= Relational1_relop2;
  Relational1_out1(2) <= Relational1_relop3;
  Relational1_out1(3) <= Relational1_relop4;
  Relational1_out1(4) <= Relational1_relop5;
  Relational1_out1(5) <= Relational1_relop6;
  Relational1_out1(6) <= Relational1_relop7;
  Relational1_out1(7) <= Relational1_relop8;
  Relational1_out1(8) <= Relational1_relop9;
  Relational1_out1(9) <= Relational1_relop10;
  Relational1_out1(10) <= Relational1_relop11;
  Relational1_out1(11) <= Relational1_relop12;
  Relational1_out1(12) <= Relational1_relop13;
  Relational1_out1(13) <= Relational1_relop14;
  Relational1_out1(14) <= Relational1_relop15;
  Relational1_out1(15) <= Relational1_relop16;
  Relational1_out1(16) <= Relational1_relop17;
  Relational1_out1(17) <= Relational1_relop18;
  Relational1_out1(18) <= Relational1_relop19;
  Relational1_out1(19) <= Relational1_relop20;
  Relational1_out1(20) <= Relational1_relop21;
  Relational1_out1(21) <= Relational1_relop22;
  Relational1_out1(22) <= Relational1_relop23;
  Relational1_out1(23) <= Relational1_relop24;
  Relational1_out1(24) <= Relational1_relop25;
  Relational1_out1(25) <= Relational1_relop26;
  Relational1_out1(26) <= Relational1_relop27;
  Relational1_out1(27) <= Relational1_relop28;
  Relational1_out1(28) <= Relational1_relop29;
  Relational1_out1(29) <= Relational1_relop30;
  Relational1_out1(30) <= Relational1_relop31;
  Relational1_out1(31) <= Relational1_relop32;
  Relational1_out1(32) <= Relational1_relop33;
  Relational1_out1(33) <= Relational1_relop34;
  Relational1_out1(34) <= Relational1_relop35;
  Relational1_out1(35) <= Relational1_relop36;
  Relational1_out1(36) <= Relational1_relop37;
  Relational1_out1(37) <= Relational1_relop38;
  Relational1_out1(38) <= Relational1_relop39;
  Relational1_out1(39) <= Relational1_relop40;
  Relational1_out1(40) <= Relational1_relop41;
  Relational1_out1(41) <= Relational1_relop42;
  Relational1_out1(42) <= Relational1_relop43;
  Relational1_out1(43) <= Relational1_relop44;
  Relational1_out1(44) <= Relational1_relop45;

  Relational1_out1_0 <= Relational1_out1(0);

  Multiport_Switch2_out1(0) <= Multiport_Switch2_out1_0;
  Multiport_Switch2_out1(1) <= Multiport_Switch2_out1_1;
  Multiport_Switch2_out1(2) <= Multiport_Switch2_out1_2;
  Multiport_Switch2_out1(3) <= Multiport_Switch2_out1_3;
  Multiport_Switch2_out1(4) <= Multiport_Switch2_out1_4;
  Multiport_Switch2_out1(5) <= Multiport_Switch2_out1_5;
  Multiport_Switch2_out1(6) <= Multiport_Switch2_out1_6;
  Multiport_Switch2_out1(7) <= Multiport_Switch2_out1_7;
  Multiport_Switch2_out1(8) <= Multiport_Switch2_out1_8;
  Multiport_Switch2_out1(9) <= Multiport_Switch2_out1_9;
  Multiport_Switch2_out1(10) <= Multiport_Switch2_out1_10;
  Multiport_Switch2_out1(11) <= Multiport_Switch2_out1_11;
  Multiport_Switch2_out1(12) <= Multiport_Switch2_out1_12;
  Multiport_Switch2_out1(13) <= Multiport_Switch2_out1_13;
  Multiport_Switch2_out1(14) <= Multiport_Switch2_out1_14;
  Multiport_Switch2_out1(15) <= Multiport_Switch2_out1_15;
  Multiport_Switch2_out1(16) <= Multiport_Switch2_out1_16;
  Multiport_Switch2_out1(17) <= Multiport_Switch2_out1_17;
  Multiport_Switch2_out1(18) <= Multiport_Switch2_out1_18;
  Multiport_Switch2_out1(19) <= Multiport_Switch2_out1_19;
  Multiport_Switch2_out1(20) <= Multiport_Switch2_out1_20;
  Multiport_Switch2_out1(21) <= Multiport_Switch2_out1_21;
  Multiport_Switch2_out1(22) <= Multiport_Switch2_out1_22;
  Multiport_Switch2_out1(23) <= Multiport_Switch2_out1_23;
  Multiport_Switch2_out1(24) <= Multiport_Switch2_out1_24;
  Multiport_Switch2_out1(25) <= Multiport_Switch2_out1_25;
  Multiport_Switch2_out1(26) <= Multiport_Switch2_out1_26;
  Multiport_Switch2_out1(27) <= Multiport_Switch2_out1_27;
  Multiport_Switch2_out1(28) <= Multiport_Switch2_out1_28;
  Multiport_Switch2_out1(29) <= Multiport_Switch2_out1_29;
  Multiport_Switch2_out1(30) <= Multiport_Switch2_out1_30;
  Multiport_Switch2_out1(31) <= Multiport_Switch2_out1_31;
  Multiport_Switch2_out1(32) <= Multiport_Switch2_out1_32;
  Multiport_Switch2_out1(33) <= Multiport_Switch2_out1_33;
  Multiport_Switch2_out1(34) <= Multiport_Switch2_out1_34;
  Multiport_Switch2_out1(35) <= Multiport_Switch2_out1_35;
  Multiport_Switch2_out1(36) <= Multiport_Switch2_out1_36;
  Multiport_Switch2_out1(37) <= Multiport_Switch2_out1_37;
  Multiport_Switch2_out1(38) <= Multiport_Switch2_out1_38;
  Multiport_Switch2_out1(39) <= Multiport_Switch2_out1_39;
  Multiport_Switch2_out1(40) <= Multiport_Switch2_out1_40;
  Multiport_Switch2_out1(41) <= Multiport_Switch2_out1_41;
  Multiport_Switch2_out1(42) <= Multiport_Switch2_out1_42;
  Multiport_Switch2_out1(43) <= Multiport_Switch2_out1_43;
  Multiport_Switch2_out1(44) <= Multiport_Switch2_out1_44;


  Multiport_Switch2_out1_dtc_gen: FOR ii1 IN 0 TO 44 GENERATE
    Multiport_Switch2_out1_dtc(ii1) <= resize(Multiport_Switch2_out1(ii1), 12);
  END GENERATE Multiport_Switch2_out1_dtc_gen;


  Multiport_Switch2_out1_dtc_0 <= Multiport_Switch2_out1_dtc(0);

  Add1_v <= signed(resize(nTheta_out1, 12));

  Add1_out1_gen: FOR t_02 IN 0 TO 44 GENERATE
    Add1_out1(t_02) <= resize(Multiport_Switch2_out1(t_02), 12) - Add1_v;
  END GENERATE Add1_out1_gen;


  Relational1_out1_1 <= Relational1_out1(1);

  Multiport_Switch2_out1_dtc_1 <= Multiport_Switch2_out1_dtc(1);

  Relational1_out1_2 <= Relational1_out1(2);

  Multiport_Switch2_out1_dtc_2 <= Multiport_Switch2_out1_dtc(2);

  Relational1_out1_3 <= Relational1_out1(3);

  Multiport_Switch2_out1_dtc_3 <= Multiport_Switch2_out1_dtc(3);

  Relational1_out1_4 <= Relational1_out1(4);

  Multiport_Switch2_out1_dtc_4 <= Multiport_Switch2_out1_dtc(4);

  Relational1_out1_5 <= Relational1_out1(5);

  Multiport_Switch2_out1_dtc_5 <= Multiport_Switch2_out1_dtc(5);

  Relational1_out1_6 <= Relational1_out1(6);

  Multiport_Switch2_out1_dtc_6 <= Multiport_Switch2_out1_dtc(6);

  Relational1_out1_7 <= Relational1_out1(7);

  Multiport_Switch2_out1_dtc_7 <= Multiport_Switch2_out1_dtc(7);

  Relational1_out1_8 <= Relational1_out1(8);

  Multiport_Switch2_out1_dtc_8 <= Multiport_Switch2_out1_dtc(8);

  Relational1_out1_9 <= Relational1_out1(9);

  Multiport_Switch2_out1_dtc_9 <= Multiport_Switch2_out1_dtc(9);

  Relational1_out1_10 <= Relational1_out1(10);

  Multiport_Switch2_out1_dtc_10 <= Multiport_Switch2_out1_dtc(10);

  Relational1_out1_11 <= Relational1_out1(11);

  Multiport_Switch2_out1_dtc_11 <= Multiport_Switch2_out1_dtc(11);

  Relational1_out1_12 <= Relational1_out1(12);

  Multiport_Switch2_out1_dtc_12 <= Multiport_Switch2_out1_dtc(12);

  Relational1_out1_13 <= Relational1_out1(13);

  Multiport_Switch2_out1_dtc_13 <= Multiport_Switch2_out1_dtc(13);

  Relational1_out1_14 <= Relational1_out1(14);

  Multiport_Switch2_out1_dtc_14 <= Multiport_Switch2_out1_dtc(14);

  Relational1_out1_15 <= Relational1_out1(15);

  Multiport_Switch2_out1_dtc_15 <= Multiport_Switch2_out1_dtc(15);

  Relational1_out1_16 <= Relational1_out1(16);

  Multiport_Switch2_out1_dtc_16 <= Multiport_Switch2_out1_dtc(16);

  Relational1_out1_17 <= Relational1_out1(17);

  Multiport_Switch2_out1_dtc_17 <= Multiport_Switch2_out1_dtc(17);

  Relational1_out1_18 <= Relational1_out1(18);

  Multiport_Switch2_out1_dtc_18 <= Multiport_Switch2_out1_dtc(18);

  Relational1_out1_19 <= Relational1_out1(19);

  Multiport_Switch2_out1_dtc_19 <= Multiport_Switch2_out1_dtc(19);

  Relational1_out1_20 <= Relational1_out1(20);

  Multiport_Switch2_out1_dtc_20 <= Multiport_Switch2_out1_dtc(20);

  Relational1_out1_21 <= Relational1_out1(21);

  Multiport_Switch2_out1_dtc_21 <= Multiport_Switch2_out1_dtc(21);

  Relational1_out1_22 <= Relational1_out1(22);

  Multiport_Switch2_out1_dtc_22 <= Multiport_Switch2_out1_dtc(22);

  Relational1_out1_23 <= Relational1_out1(23);

  Multiport_Switch2_out1_dtc_23 <= Multiport_Switch2_out1_dtc(23);

  Relational1_out1_24 <= Relational1_out1(24);

  Multiport_Switch2_out1_dtc_24 <= Multiport_Switch2_out1_dtc(24);

  Relational1_out1_25 <= Relational1_out1(25);

  Multiport_Switch2_out1_dtc_25 <= Multiport_Switch2_out1_dtc(25);

  Relational1_out1_26 <= Relational1_out1(26);

  Multiport_Switch2_out1_dtc_26 <= Multiport_Switch2_out1_dtc(26);

  Relational1_out1_27 <= Relational1_out1(27);

  Multiport_Switch2_out1_dtc_27 <= Multiport_Switch2_out1_dtc(27);

  Relational1_out1_28 <= Relational1_out1(28);

  Multiport_Switch2_out1_dtc_28 <= Multiport_Switch2_out1_dtc(28);

  Relational1_out1_29 <= Relational1_out1(29);

  Multiport_Switch2_out1_dtc_29 <= Multiport_Switch2_out1_dtc(29);

  Relational1_out1_30 <= Relational1_out1(30);

  Multiport_Switch2_out1_dtc_30 <= Multiport_Switch2_out1_dtc(30);

  Relational1_out1_31 <= Relational1_out1(31);

  Multiport_Switch2_out1_dtc_31 <= Multiport_Switch2_out1_dtc(31);

  Relational1_out1_32 <= Relational1_out1(32);

  Multiport_Switch2_out1_dtc_32 <= Multiport_Switch2_out1_dtc(32);

  Relational1_out1_33 <= Relational1_out1(33);

  Multiport_Switch2_out1_dtc_33 <= Multiport_Switch2_out1_dtc(33);

  Relational1_out1_34 <= Relational1_out1(34);

  Multiport_Switch2_out1_dtc_34 <= Multiport_Switch2_out1_dtc(34);

  Relational1_out1_35 <= Relational1_out1(35);

  Multiport_Switch2_out1_dtc_35 <= Multiport_Switch2_out1_dtc(35);

  Relational1_out1_36 <= Relational1_out1(36);

  Multiport_Switch2_out1_dtc_36 <= Multiport_Switch2_out1_dtc(36);

  Relational1_out1_37 <= Relational1_out1(37);

  Multiport_Switch2_out1_dtc_37 <= Multiport_Switch2_out1_dtc(37);

  Relational1_out1_38 <= Relational1_out1(38);

  Multiport_Switch2_out1_dtc_38 <= Multiport_Switch2_out1_dtc(38);

  Relational1_out1_39 <= Relational1_out1(39);

  Multiport_Switch2_out1_dtc_39 <= Multiport_Switch2_out1_dtc(39);

  Relational1_out1_40 <= Relational1_out1(40);

  Multiport_Switch2_out1_dtc_40 <= Multiport_Switch2_out1_dtc(40);

  Relational1_out1_41 <= Relational1_out1(41);

  Multiport_Switch2_out1_dtc_41 <= Multiport_Switch2_out1_dtc(41);

  Relational1_out1_42 <= Relational1_out1(42);

  Multiport_Switch2_out1_dtc_42 <= Multiport_Switch2_out1_dtc(42);

  Relational1_out1_43 <= Relational1_out1(43);

  Multiport_Switch2_out1_dtc_43 <= Multiport_Switch2_out1_dtc(43);

  Relational1_out1_44 <= Relational1_out1(44);

  Multiport_Switch2_out1_dtc_44 <= Multiport_Switch2_out1_dtc(44);

  High1_out1 <= to_unsigned(16#2C#, 8);

  Add1_out1_0 <= Add1_out1(0);

  
  Multiport_Switch3_out1_0 <= Multiport_Switch2_out1_dtc_0 WHEN Relational1_out1_0 = '0' ELSE
      Add1_out1_0;

  Add1_out1_1 <= Add1_out1(1);

  
  Multiport_Switch3_out1_1 <= Multiport_Switch2_out1_dtc_1 WHEN Relational1_out1_1 = '0' ELSE
      Add1_out1_1;

  Add1_out1_2 <= Add1_out1(2);

  
  Multiport_Switch3_out1_2 <= Multiport_Switch2_out1_dtc_2 WHEN Relational1_out1_2 = '0' ELSE
      Add1_out1_2;

  Add1_out1_3 <= Add1_out1(3);

  
  Multiport_Switch3_out1_3 <= Multiport_Switch2_out1_dtc_3 WHEN Relational1_out1_3 = '0' ELSE
      Add1_out1_3;

  Add1_out1_4 <= Add1_out1(4);

  
  Multiport_Switch3_out1_4 <= Multiport_Switch2_out1_dtc_4 WHEN Relational1_out1_4 = '0' ELSE
      Add1_out1_4;

  Add1_out1_5 <= Add1_out1(5);

  
  Multiport_Switch3_out1_5 <= Multiport_Switch2_out1_dtc_5 WHEN Relational1_out1_5 = '0' ELSE
      Add1_out1_5;

  Add1_out1_6 <= Add1_out1(6);

  
  Multiport_Switch3_out1_6 <= Multiport_Switch2_out1_dtc_6 WHEN Relational1_out1_6 = '0' ELSE
      Add1_out1_6;

  Add1_out1_7 <= Add1_out1(7);

  
  Multiport_Switch3_out1_7 <= Multiport_Switch2_out1_dtc_7 WHEN Relational1_out1_7 = '0' ELSE
      Add1_out1_7;

  Add1_out1_8 <= Add1_out1(8);

  
  Multiport_Switch3_out1_8 <= Multiport_Switch2_out1_dtc_8 WHEN Relational1_out1_8 = '0' ELSE
      Add1_out1_8;

  Add1_out1_9 <= Add1_out1(9);

  
  Multiport_Switch3_out1_9 <= Multiport_Switch2_out1_dtc_9 WHEN Relational1_out1_9 = '0' ELSE
      Add1_out1_9;

  Add1_out1_10 <= Add1_out1(10);

  
  Multiport_Switch3_out1_10 <= Multiport_Switch2_out1_dtc_10 WHEN Relational1_out1_10 = '0' ELSE
      Add1_out1_10;

  Add1_out1_11 <= Add1_out1(11);

  
  Multiport_Switch3_out1_11 <= Multiport_Switch2_out1_dtc_11 WHEN Relational1_out1_11 = '0' ELSE
      Add1_out1_11;

  Add1_out1_12 <= Add1_out1(12);

  
  Multiport_Switch3_out1_12 <= Multiport_Switch2_out1_dtc_12 WHEN Relational1_out1_12 = '0' ELSE
      Add1_out1_12;

  Add1_out1_13 <= Add1_out1(13);

  
  Multiport_Switch3_out1_13 <= Multiport_Switch2_out1_dtc_13 WHEN Relational1_out1_13 = '0' ELSE
      Add1_out1_13;

  Add1_out1_14 <= Add1_out1(14);

  
  Multiport_Switch3_out1_14 <= Multiport_Switch2_out1_dtc_14 WHEN Relational1_out1_14 = '0' ELSE
      Add1_out1_14;

  Add1_out1_15 <= Add1_out1(15);

  
  Multiport_Switch3_out1_15 <= Multiport_Switch2_out1_dtc_15 WHEN Relational1_out1_15 = '0' ELSE
      Add1_out1_15;

  Add1_out1_16 <= Add1_out1(16);

  
  Multiport_Switch3_out1_16 <= Multiport_Switch2_out1_dtc_16 WHEN Relational1_out1_16 = '0' ELSE
      Add1_out1_16;

  Add1_out1_17 <= Add1_out1(17);

  
  Multiport_Switch3_out1_17 <= Multiport_Switch2_out1_dtc_17 WHEN Relational1_out1_17 = '0' ELSE
      Add1_out1_17;

  Add1_out1_18 <= Add1_out1(18);

  
  Multiport_Switch3_out1_18 <= Multiport_Switch2_out1_dtc_18 WHEN Relational1_out1_18 = '0' ELSE
      Add1_out1_18;

  Add1_out1_19 <= Add1_out1(19);

  
  Multiport_Switch3_out1_19 <= Multiport_Switch2_out1_dtc_19 WHEN Relational1_out1_19 = '0' ELSE
      Add1_out1_19;

  Add1_out1_20 <= Add1_out1(20);

  
  Multiport_Switch3_out1_20 <= Multiport_Switch2_out1_dtc_20 WHEN Relational1_out1_20 = '0' ELSE
      Add1_out1_20;

  Add1_out1_21 <= Add1_out1(21);

  
  Multiport_Switch3_out1_21 <= Multiport_Switch2_out1_dtc_21 WHEN Relational1_out1_21 = '0' ELSE
      Add1_out1_21;

  Add1_out1_22 <= Add1_out1(22);

  
  Multiport_Switch3_out1_22 <= Multiport_Switch2_out1_dtc_22 WHEN Relational1_out1_22 = '0' ELSE
      Add1_out1_22;

  Add1_out1_23 <= Add1_out1(23);

  
  Multiport_Switch3_out1_23 <= Multiport_Switch2_out1_dtc_23 WHEN Relational1_out1_23 = '0' ELSE
      Add1_out1_23;

  Add1_out1_24 <= Add1_out1(24);

  
  Multiport_Switch3_out1_24 <= Multiport_Switch2_out1_dtc_24 WHEN Relational1_out1_24 = '0' ELSE
      Add1_out1_24;

  Add1_out1_25 <= Add1_out1(25);

  
  Multiport_Switch3_out1_25 <= Multiport_Switch2_out1_dtc_25 WHEN Relational1_out1_25 = '0' ELSE
      Add1_out1_25;

  Add1_out1_26 <= Add1_out1(26);

  
  Multiport_Switch3_out1_26 <= Multiport_Switch2_out1_dtc_26 WHEN Relational1_out1_26 = '0' ELSE
      Add1_out1_26;

  Add1_out1_27 <= Add1_out1(27);

  
  Multiport_Switch3_out1_27 <= Multiport_Switch2_out1_dtc_27 WHEN Relational1_out1_27 = '0' ELSE
      Add1_out1_27;

  Add1_out1_28 <= Add1_out1(28);

  
  Multiport_Switch3_out1_28 <= Multiport_Switch2_out1_dtc_28 WHEN Relational1_out1_28 = '0' ELSE
      Add1_out1_28;

  Add1_out1_29 <= Add1_out1(29);

  
  Multiport_Switch3_out1_29 <= Multiport_Switch2_out1_dtc_29 WHEN Relational1_out1_29 = '0' ELSE
      Add1_out1_29;

  Add1_out1_30 <= Add1_out1(30);

  
  Multiport_Switch3_out1_30 <= Multiport_Switch2_out1_dtc_30 WHEN Relational1_out1_30 = '0' ELSE
      Add1_out1_30;

  Add1_out1_31 <= Add1_out1(31);

  
  Multiport_Switch3_out1_31 <= Multiport_Switch2_out1_dtc_31 WHEN Relational1_out1_31 = '0' ELSE
      Add1_out1_31;

  Add1_out1_32 <= Add1_out1(32);

  
  Multiport_Switch3_out1_32 <= Multiport_Switch2_out1_dtc_32 WHEN Relational1_out1_32 = '0' ELSE
      Add1_out1_32;

  Add1_out1_33 <= Add1_out1(33);

  
  Multiport_Switch3_out1_33 <= Multiport_Switch2_out1_dtc_33 WHEN Relational1_out1_33 = '0' ELSE
      Add1_out1_33;

  Add1_out1_34 <= Add1_out1(34);

  
  Multiport_Switch3_out1_34 <= Multiport_Switch2_out1_dtc_34 WHEN Relational1_out1_34 = '0' ELSE
      Add1_out1_34;

  Add1_out1_35 <= Add1_out1(35);

  
  Multiport_Switch3_out1_35 <= Multiport_Switch2_out1_dtc_35 WHEN Relational1_out1_35 = '0' ELSE
      Add1_out1_35;

  Add1_out1_36 <= Add1_out1(36);

  
  Multiport_Switch3_out1_36 <= Multiport_Switch2_out1_dtc_36 WHEN Relational1_out1_36 = '0' ELSE
      Add1_out1_36;

  Add1_out1_37 <= Add1_out1(37);

  
  Multiport_Switch3_out1_37 <= Multiport_Switch2_out1_dtc_37 WHEN Relational1_out1_37 = '0' ELSE
      Add1_out1_37;

  Add1_out1_38 <= Add1_out1(38);

  
  Multiport_Switch3_out1_38 <= Multiport_Switch2_out1_dtc_38 WHEN Relational1_out1_38 = '0' ELSE
      Add1_out1_38;

  Add1_out1_39 <= Add1_out1(39);

  
  Multiport_Switch3_out1_39 <= Multiport_Switch2_out1_dtc_39 WHEN Relational1_out1_39 = '0' ELSE
      Add1_out1_39;

  Add1_out1_40 <= Add1_out1(40);

  
  Multiport_Switch3_out1_40 <= Multiport_Switch2_out1_dtc_40 WHEN Relational1_out1_40 = '0' ELSE
      Add1_out1_40;

  Add1_out1_41 <= Add1_out1(41);

  
  Multiport_Switch3_out1_41 <= Multiport_Switch2_out1_dtc_41 WHEN Relational1_out1_41 = '0' ELSE
      Add1_out1_41;

  Add1_out1_42 <= Add1_out1(42);

  
  Multiport_Switch3_out1_42 <= Multiport_Switch2_out1_dtc_42 WHEN Relational1_out1_42 = '0' ELSE
      Add1_out1_42;

  Add1_out1_43 <= Add1_out1(43);

  
  Multiport_Switch3_out1_43 <= Multiport_Switch2_out1_dtc_43 WHEN Relational1_out1_43 = '0' ELSE
      Add1_out1_43;

  Add1_out1_44 <= Add1_out1(44);

  
  Multiport_Switch3_out1_44 <= Multiport_Switch2_out1_dtc_44 WHEN Relational1_out1_44 = '0' ELSE
      Add1_out1_44;

  Multiport_Switch3_out1(0) <= Multiport_Switch3_out1_0;
  Multiport_Switch3_out1(1) <= Multiport_Switch3_out1_1;
  Multiport_Switch3_out1(2) <= Multiport_Switch3_out1_2;
  Multiport_Switch3_out1(3) <= Multiport_Switch3_out1_3;
  Multiport_Switch3_out1(4) <= Multiport_Switch3_out1_4;
  Multiport_Switch3_out1(5) <= Multiport_Switch3_out1_5;
  Multiport_Switch3_out1(6) <= Multiport_Switch3_out1_6;
  Multiport_Switch3_out1(7) <= Multiport_Switch3_out1_7;
  Multiport_Switch3_out1(8) <= Multiport_Switch3_out1_8;
  Multiport_Switch3_out1(9) <= Multiport_Switch3_out1_9;
  Multiport_Switch3_out1(10) <= Multiport_Switch3_out1_10;
  Multiport_Switch3_out1(11) <= Multiport_Switch3_out1_11;
  Multiport_Switch3_out1(12) <= Multiport_Switch3_out1_12;
  Multiport_Switch3_out1(13) <= Multiport_Switch3_out1_13;
  Multiport_Switch3_out1(14) <= Multiport_Switch3_out1_14;
  Multiport_Switch3_out1(15) <= Multiport_Switch3_out1_15;
  Multiport_Switch3_out1(16) <= Multiport_Switch3_out1_16;
  Multiport_Switch3_out1(17) <= Multiport_Switch3_out1_17;
  Multiport_Switch3_out1(18) <= Multiport_Switch3_out1_18;
  Multiport_Switch3_out1(19) <= Multiport_Switch3_out1_19;
  Multiport_Switch3_out1(20) <= Multiport_Switch3_out1_20;
  Multiport_Switch3_out1(21) <= Multiport_Switch3_out1_21;
  Multiport_Switch3_out1(22) <= Multiport_Switch3_out1_22;
  Multiport_Switch3_out1(23) <= Multiport_Switch3_out1_23;
  Multiport_Switch3_out1(24) <= Multiport_Switch3_out1_24;
  Multiport_Switch3_out1(25) <= Multiport_Switch3_out1_25;
  Multiport_Switch3_out1(26) <= Multiport_Switch3_out1_26;
  Multiport_Switch3_out1(27) <= Multiport_Switch3_out1_27;
  Multiport_Switch3_out1(28) <= Multiport_Switch3_out1_28;
  Multiport_Switch3_out1(29) <= Multiport_Switch3_out1_29;
  Multiport_Switch3_out1(30) <= Multiport_Switch3_out1_30;
  Multiport_Switch3_out1(31) <= Multiport_Switch3_out1_31;
  Multiport_Switch3_out1(32) <= Multiport_Switch3_out1_32;
  Multiport_Switch3_out1(33) <= Multiport_Switch3_out1_33;
  Multiport_Switch3_out1(34) <= Multiport_Switch3_out1_34;
  Multiport_Switch3_out1(35) <= Multiport_Switch3_out1_35;
  Multiport_Switch3_out1(36) <= Multiport_Switch3_out1_36;
  Multiport_Switch3_out1(37) <= Multiport_Switch3_out1_37;
  Multiport_Switch3_out1(38) <= Multiport_Switch3_out1_38;
  Multiport_Switch3_out1(39) <= Multiport_Switch3_out1_39;
  Multiport_Switch3_out1(40) <= Multiport_Switch3_out1_40;
  Multiport_Switch3_out1(41) <= Multiport_Switch3_out1_41;
  Multiport_Switch3_out1(42) <= Multiport_Switch3_out1_42;
  Multiport_Switch3_out1(43) <= Multiport_Switch3_out1_43;
  Multiport_Switch3_out1(44) <= Multiport_Switch3_out1_44;


  Data_Type_Conversion_out1_gen: FOR ii2 IN 0 TO 44 GENERATE
    Data_Type_Conversion_out1(ii2) <= unsigned(Multiport_Switch3_out1(ii2)(7 DOWNTO 0));
  END GENERATE Data_Type_Conversion_out1_gen;



  Add4_out1_gen: FOR t_03 IN 0 TO 44 GENERATE
    Add4_out1(t_03) <= High1_out1 - Data_Type_Conversion_out1(t_03);
  END GENERATE Add4_out1_gen;


  Selector4_out1(0) <= Add4_out1(44);
  Selector4_out1(1) <= Add4_out1(43);
  Selector4_out1(2) <= Add4_out1(42);
  Selector4_out1(3) <= Add4_out1(41);
  Selector4_out1(4) <= Add4_out1(40);
  Selector4_out1(5) <= Add4_out1(39);
  Selector4_out1(6) <= Add4_out1(38);
  Selector4_out1(7) <= Add4_out1(37);
  Selector4_out1(8) <= Add4_out1(36);
  Selector4_out1(9) <= Add4_out1(35);
  Selector4_out1(10) <= Add4_out1(34);
  Selector4_out1(11) <= Add4_out1(33);
  Selector4_out1(12) <= Add4_out1(32);
  Selector4_out1(13) <= Add4_out1(31);
  Selector4_out1(14) <= Add4_out1(30);
  Selector4_out1(15) <= Add4_out1(29);
  Selector4_out1(16) <= Add4_out1(28);
  Selector4_out1(17) <= Add4_out1(27);
  Selector4_out1(18) <= Add4_out1(26);
  Selector4_out1(19) <= Add4_out1(25);
  Selector4_out1(20) <= Add4_out1(24);
  Selector4_out1(21) <= Add4_out1(23);
  Selector4_out1(22) <= Add4_out1(22);
  Selector4_out1(23) <= Add4_out1(21);
  Selector4_out1(24) <= Add4_out1(20);
  Selector4_out1(25) <= Add4_out1(19);
  Selector4_out1(26) <= Add4_out1(18);
  Selector4_out1(27) <= Add4_out1(17);
  Selector4_out1(28) <= Add4_out1(16);
  Selector4_out1(29) <= Add4_out1(15);
  Selector4_out1(30) <= Add4_out1(14);
  Selector4_out1(31) <= Add4_out1(13);
  Selector4_out1(32) <= Add4_out1(12);
  Selector4_out1(33) <= Add4_out1(11);
  Selector4_out1(34) <= Add4_out1(10);
  Selector4_out1(35) <= Add4_out1(9);
  Selector4_out1(36) <= Add4_out1(8);
  Selector4_out1(37) <= Add4_out1(7);
  Selector4_out1(38) <= Add4_out1(6);
  Selector4_out1(39) <= Add4_out1(5);
  Selector4_out1(40) <= Add4_out1(4);
  Selector4_out1(41) <= Add4_out1(3);
  Selector4_out1(42) <= Add4_out1(2);
  Selector4_out1(43) <= Add4_out1(1);
  Selector4_out1(44) <= Add4_out1(0);

  outputgen: FOR k IN 0 TO 44 GENERATE
    Index(k) <= std_logic_vector(Selector4_out1(k));
  END GENERATE;

END rtl;

