SLStudio.Utils.RemoveHighlighting(get_param('hybrid_lht', 'handle'));
SLStudio.Utils.RemoveHighlighting(get_param('gm_hybrid_lht', 'handle'));
annotate_port('gm_hybrid_lht/Hybrid LHT/Hybrid LHT Kernel/Gradient Kernel System/Hough Kernel/Look Ahead Hough/Look Ahead Hough Symmetric', 0, 1, '');
annotate_port('hybrid_lht/Hybrid LHT/Hybrid LHT Kernel/Gradient Kernel System/Hough Kernel/Look Ahead Hough/Look Ahead Hough Symmetric', 0, 1, '');
annotate_port('gm_hybrid_lht/Hybrid LHT/Hybrid LHT Kernel/Gradient Kernel System/Hough Kernel/Look Ahead Hough/Look Ahead Hough Symmetric/MATLAB Function', 0, 1, '');
annotate_port('hybrid_lht/Hybrid LHT/Hybrid LHT Kernel/Gradient Kernel System/Hough Kernel/Look Ahead Hough/Look Ahead Hough Symmetric/MATLAB Function', 0, 1, '');
annotate_port('gm_hybrid_lht/Hybrid LHT/Hybrid LHT Kernel/Gradient Kernel System/Hough Kernel/Look Ahead Hough/Look Ahead Hough Symmetric/Constant', 0, 1, '');
annotate_port('hybrid_lht/Hybrid LHT/Hybrid LHT Kernel/Gradient Kernel System/Hough Kernel/Look Ahead Hough/Look Ahead Hough Symmetric/Constant', 0, 1, '');
annotate_port('gm_hybrid_lht/Hybrid LHT/Hybrid LHT Kernel/Gradient Kernel System/Hough Kernel/Look Ahead Hough/Look Ahead Hough Symmetric/Constant1', 0, 1, '');
annotate_port('hybrid_lht/Hybrid LHT/Hybrid LHT Kernel/Gradient Kernel System/Hough Kernel/Look Ahead Hough/Look Ahead Hough Symmetric/Constant1', 0, 1, '');
annotate_port('gm_hybrid_lht/Hybrid LHT/Hybrid LHT Kernel/Gradient Kernel System/Hough Kernel/Look Ahead Hough/Look Ahead Hough Symmetric/SineROM', 0, 1, '');
annotate_port('hybrid_lht/Hybrid LHT/Hybrid LHT Kernel/Gradient Kernel System/Hough Kernel/Look Ahead Hough/Look Ahead Hough Symmetric/SineROM', 0, 1, '');
annotate_port('gm_hybrid_lht/Hybrid LHT/Hybrid LHT Kernel/Gradient Kernel System/Hough Kernel/Look Ahead Hough/Look Ahead Hough Symmetric/row_0', 0, 1, '');
annotate_port('hybrid_lht/Hybrid LHT/Hybrid LHT Kernel/Gradient Kernel System/Hough Kernel/Look Ahead Hough/Look Ahead Hough Symmetric/row_0', 0, 1, '');
annotate_port('gm_hybrid_lht/Hybrid LHT/Hybrid LHT Kernel/Gradient Kernel System/Hough Kernel/Look Ahead Hough/Look Ahead Hough Symmetric/theta_index', 0, 1, '');
annotate_port('hybrid_lht/Hybrid LHT/Hybrid LHT Kernel/Gradient Kernel System/Hough Kernel/Look Ahead Hough/Look Ahead Hough Symmetric/theta_index', 0, 1, '');
annotate_port('gm_hybrid_lht/Hybrid LHT/Hybrid LHT Kernel/Gradient Kernel System/Hough Kernel/Look Ahead Hough/Look Ahead Hough Symmetric/Relational Operator', 0, 1, '');
annotate_port('hybrid_lht/Hybrid LHT/Hybrid LHT Kernel/Gradient Kernel System/Hough Kernel/Look Ahead Hough/Look Ahead Hough Symmetric/Relational Operator', 0, 1, '');
