-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj_720p\hdlsrc\hybrid_lht\Look_Ahead_Hough.vhd
-- Created: 2020-03-05 09:20:25
-- 
-- Generated by MATLAB 9.7 and HDL Coder 3.15
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Look_Ahead_Hough
-- Source Path: hybrid_lht/Hybrid LHT/Hybrid LHT Kernel/Gradient Kernel System/Hough Kernel/Look Ahead Hough
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Hybrid_LHT_pkg.ALL;

ENTITY Look_Ahead_Hough IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Y                                 :   IN    std_logic_vector(9 DOWNTO 0);  -- sfix10
        eol                               :   IN    std_logic;
        ysin                              :   OUT   vector_of_std_logic_vector10(0 TO 179)  -- sfix10 [180]
        );
END Look_Ahead_Hough;


ARCHITECTURE rtl OF Look_Ahead_Hough IS

  -- Component Declarations
  COMPONENT Look_Ahead_Hough_Symmetric
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Y                               :   IN    std_logic_vector(9 DOWNTO 0);  -- sfix10
          eol                             :   IN    std_logic;
          ysin                            :   OUT   vector_of_std_logic_vector10(0 TO 179)  -- sfix10 [180]
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Look_Ahead_Hough_Symmetric
    USE ENTITY work.Look_Ahead_Hough_Symmetric(rtl);

  -- Signals
  SIGNAL Look_Ahead_Hough_Symmetric_out1  : vector_of_std_logic_vector10(0 TO 179);  -- ufix10 [180]

BEGIN
  u_Look_Ahead_Hough_Symmetric : Look_Ahead_Hough_Symmetric
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              Y => Y,  -- sfix10
              eol => eol,
              ysin => Look_Ahead_Hough_Symmetric_out1  -- sfix10 [180]
              );

  ysin <= Look_Ahead_Hough_Symmetric_out1;

END rtl;

